### PR TITLE
[Keyboard] Add Quarkeys Z67

### PR DESCRIPTION
**Pull request by tommyamoszhao**
## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Xelus22** [comment]
Please link your QMK PR

**Comment by tommyamoszhao** [comment]
@Xelus22 Sure, here's the link: https://github.com/qmk/qmk_firmware/tree/master/keyboards/quarkeys/z67     It's already been merged into qmk_master. Appreciate. TommyZ

**Comment by Xelus22** [comment]
It looks like you have some duplicate ones for the VIA V3 versions for hotswap and soldered version? Could you please take a look again

**Comment by tommyamoszhao** [comment]
@Xelus22 thx for pointing out, duplicated file deleted. Sorry for the careless work

**Comment by Xelus22** [comment]
It seems your V2 has `qmk_rgblight` but your V3 has no lighting? is this correct?

**Comment by tommyamoszhao** [comment]
@Xelus22 thx for the heads up, I'll go through checks for all the keyboard under quarkeys again.  :)

**Comment by tommyamoszhao** [comment]
@Xelus22 Hi Xelus22, is there any way that both RGBLIGHT & RGB_MATRIX menu code stay in one json file so users get to choose what they prefer in qmk firmware without changing the json file for VIA? Reason is if not, there needs to have to sets of firmware(with different product ID) for both light effect, yet, all other codes are exactly the same. Best, TommyZ

**Comment by Xelus22** [comment]
hi @tommyamoszhao im not 100% sure as I do not have a keyboard with BOTH rgb matrix and rgb light. However I do think you may be able to do this

`"menus" : ["qmk_rgblight", "qmk_rgb_matrix"]

Please experiment :)

**Comment by tommyamoszhao** [comment]
hi @Xelus22 , tried this method, halfly worked. It did went through objects check during loading, and showed two 'LIGHTING' lables in UI, but non of them has sub-menu when selected, I guess it confuses on selecting lighting codes during runtime. I'll just select one as the default lighting setup. Best, TommyZ

**Comment by tommyamoszhao** [comment]
Hi @Xelus22, default light effects are set, and tested. Appreciated, Best, TommyZ

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
