### PR TITLE
Add PrimeKB PCBs to VIA

### PR DESCRIPTION
**Pull request by holtenc**
## Description

Moved prime_e.json from ../other to /primekb. Added additional PrimeKB PCBs that are in circulation

## Types of Changes

- [x] Adding a keyboard to VIA
- [x] Changing a keyboard already in VIA
- [ ] Bug fix
- [ ] Documentation

## Checklist

- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] The QMK firmware can be built using QMK master repo.

### CODE REVIEW

**Comment by Wilba6582** [comment]
Prime_EXL - do you want to add rotated keys like Prime_EXL_Plus? this doesn't have any layout options? (like split/2U backspace?)

Prime_EXL_Plus - this doesn't have any layout options? (like split/2U backspace?)

Prime_L - this doesnt have any layout options?

Prime_L_V2 - split backspace keys are overlapping, can move them to the right side

Prime_M - the layout options are overlapping, they can be moved off to the side

VIA will shift them to where they would be. The "shape" of the keycaps in the layout options must match, so it knows how to shift them in place (e.g. the "0,1" keys will be shifted to where the "0,0" keys are in the layout).

**Comment by holtenc** [comment]
Prime_EXL- I'll update to rotated keys. No layout options
Prime_EXL_Plus - No layout options
Prime_L - No layout options
Prime_L_v2 - I'll move them. Initially had them off to the side but assumed they were supposed to overlap due to how Prime_M layout reacted in VIA designer. See below. 
Prime_M - Initially I had them off to the sides but I couldn't get VIA to render them correctly unless they were overlaid in the "correct" position. I'll play with it some more.

**Comment by holtenc** [comment]
all done. thx wilba

**Comment by Wilba6582** [comment]
thanks!

**Pull request merged**
