### PR TITLE
Add support for the ErgoDox EZ.

### PR DESCRIPTION
**Pull request by awpr**
## Description

Add support for the ErgoDox EZ.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/11305

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by drashna** [comment]
Just a heads up here, you should ... ideally have 3 configs here, `ergodox_ez`, `ergodox_ez/shine`, and `ergodox_ez/glow`.  This is because there is a version with per key RGB, a version with rgblight (underglow), and a version without either (but no version with both).  

The VIA keymap in QMK Firmware will support all three, no issues.  But to support all three in the VIA app, you need the three different json's.

**Comment by awpr** [comment]
I don't have all three versions of the keyboard to develop configs on.  This PR is meant to add support for the original model with no LEDs; I'm not sure it'd be a good idea for me to try to add a per-key RGB keyboard without any way to test the config.

**Comment by pvinis** [comment]
I have the original too, and I'm happy to test this. How 😬?

**Comment by drashna** [comment]
I can test all 3, actually. 

@pvinis download the json here, load that into the design tab in the VIA app.  Then compile+flash the VIA keymap in the QMK repo (you may need to pull down the code for that keymap, too)

**Pull request closed without merging**
