### PR TITLE
add support for navi60 

### PR DESCRIPTION
**Pull request by DeskDaily**
## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/19253

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by yiancar** [comment]
Hello, Can you please fix the link to the qmk PR. Also can you please create a v3 json as v2 jsons are unsupported by latest versions of QMK.

**Comment by DeskDaily** [comment]
hello @yiancar so I need to create both a v2 and v3 json? is that correct?

**Comment by yiancar** [comment]
Either only v3 or both v2 and v3

**Comment by yiancar** [comment]
Cheers thanks:)

**Pull request merged**
