### PR TITLE
Add support for era/klein

### PR DESCRIPTION
**Pull request by eerraa**
Add support for era/klein

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/22127/commits/073204e31b58ff3f0ccec9badd813f1c6a843fcd
https://github.com/qmk/qmk_firmware/pull/22127

## Checklist

- [ ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Xelus22** [comment]
image

this is NOT merged. tick the checklist again when it is.

**Comment by eerraa** [comment]
@Xelus22 
Sorry, I didn't check.
It has already been merged into QMK:master. However, an update to QMK:devolop is in progress.
Should I wait for the merge into QMK:devolop to complete?

**Comment by Xelus22** [comment]
> Should I wait for the merge into QMK:devolop to complete?

Unfortunately we do not merge boards that are only merged to develop. The most updated must be in master.
This is because the firmwares generated on `caniusevia` website are from the master branch. Not from develop since that is "beta"/"nightly" firmware.

**Comment by eerraa** [comment]
@Xelus22 
Thank you for your kind explanation.
Since it takes too long to merge from QMK:devolop to QMK:master, we will merge the new firmware into qmk:master under the name alpha version.
For me, not only GitHub but also English is a big barrier, so I do a lot of stupid things.
I would be grateful if you could understand my situation.

**Comment by Xelus22** [comment]
> "The most updated must be in master." does that mean that the most recent update must exist in the master branch and not in devolop?

Correct , in master branch.

I will have to talk to the other VIA maintainers on this one since the develop -> master cycle is quite long, and updates... are slow

**Pull request closed without merging**
