### PR TITLE
Added support for Caticorn (Solder & Hotswap)

### PR DESCRIPTION
**Pull request by HorrorTroll**
## Description

Added support for Caticorn (Solder & Hotswap)

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/19138

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by HorrorTroll** [comment]
Hi @Xelus22, I've just re-open the PR and fixed all the issues. If you have time, feel free to take a look. Thanks

**Comment by Xelus22** [comment]
Does this require V2 definitons? prefer not to since that is only for legacy boards. I believe 0.19 QMK already had VIA protocol V11/12 so that has V3 definition usage.

**Comment by HorrorTroll** [comment]
The keyboard was been using firmware that was compiled on 0.18, probably I’ll just reflash with newer QMK. Thanks, i’ll deleted v2 files

**Comment by Xelus22** [comment]
@HorrorTroll does devil68 require legacy v2?

**Comment by HorrorTroll** [comment]
@Xelus22 yes, i've been flashed really old firmware on it and sold that PCB long ago. So, should be better to keep legacy board for that one.

**Pull request merged**
