### PR TITLE
add qk65 json files by qwertykeys

### PR DESCRIPTION
**Pull request by owlab-git**
## Description

Added support for PCB for the Qwertykeys qk65

## QMK Pull Request 

[qmk/qmk_firmware#16491](https://github.com/qmk/qmk_firmware/pull/16491)

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by owlab-git** [comment]
Please check, Thanks.

**Comment by owlab-git** [comment]
Bump

**Comment by owlab-git** [comment]
Please check, Thanks

**Comment by yiancar** [comment]
Cheers thanks!

**Pull request merged**
