### PR TITLE
Add Rebound Rev 4

### PR DESCRIPTION
**Pull request by Rossman360**
## Checklist

- [ x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [ x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [ ] I have tested this keyboard definition with firmware on a device.
- [ x] I have assigned alpha keys and modifier keys with the correct colors.
- [ x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Wilba6582** [comment]
needs QMK PR

**Comment by Rossman360** [comment]
> needs QMK PR

https://github.com/qmk/qmk_firmware/pull/12268

**Comment by Rossman360** [comment]
well, sorry that. I accidentally blew up a QMK PR and this one. I've now got two keyboards here, both under the same open QMK PR: https://github.com/qmk/qmk_firmware/pull/12268

**Comment by Rossman360** [comment]
This is back to just being one board again, Rebound rev 4

**Pull request merged**
