### PR TITLE
S7 Elephant Rev2

### PR DESCRIPTION
**Pull request by mechmerlin**
## Description

VIA support for S7 Elephant Rev2

## QMK Pull Request 

~~https://github.com/qmk/qmk_firmware/pull/9277~~

https://github.com/qmk/qmk_firmware/pull/9398

PR done by mudkipmao

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by MudkipMao** [comment]
Hey Merlin, can you update the QMK PR link up there? I messed up my original branch while rebasing. The new pull request is here: https://github.com/qmk/qmk_firmware/pull/9398

**Comment by mechmerlin** [comment]
> Hey Merlin, can you update the QMK PR link up there? I messed up my original branch while rebasing. The new pull request is here: [qmk/qmk_firmware#9398](https://github.com/qmk/qmk_firmware/pull/9398)

Done!

**Comment by Wilba6582** [comment]
The QMK PR was merged into a breaking change branch. Remind me when this gets into QMK master.

**Comment by MudkipMao** [comment]
It was merged into master in this commit: https://github.com/qmk/qmk_firmware/commit/622e94c6cdf6a307ee87b6add974def647979f15

**Pull request merged**
