### PR TITLE
add pluto keyboard support

### PR DESCRIPTION
**Pull request by moyi4681**
## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/21225

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Review by Xelus22 — CHANGES_REQUESTED** [review]
image

this looks incorrect?

Also please add colouring to the keys.
https://www.caniusevia.com/docs/layouts#kle-json-rules

**Comment by moyi4681** [comment]
[https://imgur.com/sC0DU01]
LGTM

**Comment by moyi4681** [comment]
> [https://imgur.com/sC0DU01](https://imgur.com/sC0DU01)
LGTM

**Comment by moyi4681** [comment]
image
LGTM

**Review by Xelus22 — CHANGES_REQUESTED** [review]
https://www.caniusevia.com/docs/layouts#kle-json-rules

please colour the json

**Review by Xelus22 — CHANGES_REQUESTED** [review]
image

please move the keys out. (sorry i just saw it is coloured now)

**Comment by moyi4681** [comment]
> image
> 
> please move the keys out. (sorry i just saw it is coloured now)

pls check again, thanks

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
