### PR TITLE
Add Ace of Spades definition

### PR DESCRIPTION
**Pull request by rys**
Adds support for the Ace of Spades, a custom fixed layout ISO TKL designed by tpk.

## Description

Ace of Spades is an ISO TKL with a fixed layout with no customisation. Tested on a production PCB using VIA v1.2.7.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/9128

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by rys** [comment]
The designer has slightly changed the name, so I've pushed that in 730f1e1, and I've also renamed it in the associated QMK commit.

**Comment by rys** [comment]
The QMK changes made it to master 🥳

**Comment by Wilba6582** [comment]
Can you fix the colors to be consistent with the others:

https://caniusevia.com/docs/layouts#kle-json-rules

**Comment by rys** [comment]
The designer wants to use the Ace of Spades name for other boards and all this one just the TKL, so the directory structure has be changed to suit. Also fixed up the colours to match the required KLE colours as requested.

**Pull request merged**
