### PR TITLE
Add f60 layouts

### PR DESCRIPTION
**Pull request by scottywei**
## Description

Add more supported layouts for the F60

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/14763

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Review by gaoyajun02 — APPROVED** [review]
LGTM, Merged

**Comment by kb-elmo** [comment]
Full right shift seems to be missing now?

**Comment by scottywei** [comment]
> Full right shift seems to be missing now?
Hmmm, All possible right shift switch holes are in the same position of the matrix, so it's still necessary to add an option for full right shift only?

**Comment by kb-elmo** [comment]
> Hmmm, All possible right shift switch holes are in the same position of the matrix, so it's still necessary to add an option for full right shift only?

The layouts in VIA should ideally represent the actual physical layout of the keyboard.
So if someone builds the board with a full right shift they should be able to select that in the layout options.

**Comment by scottywei** [comment]
> > Hmmm, All possible right shift switch holes are in the same position of the matrix, so it's still necessary to add an option for full right shift only?
> 
> The layouts in VIA should ideally represent the actual physical layout of the keyboard. So if someone builds the board with a full right shift they should be able to select that in the layout options.

Ok, thanks for reminding me, I'll add it back

**Comment by yiancar** [comment]
Hello, Let me know when ur happy with this so we can merge.

**Comment by yiancar** [comment]
closing as no response

**Pull request closed without merging**
