### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by anubhavd7**
## Checklist

- [ x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [ ] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x ] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x ] I have formatted the JSON file to have consistent formatting with the rest of the repository.
- [x ] I have tested this keyboard definition using VIA's "Design" tab.
- [x ] I have tested this keyboard definition with firmware on a device.
- [ x] I have assigned alpha keys and modifier keys with the correct colors.
- [x ] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Cipulot** [comment]
You might want to re-read the documentation on V3 options and also the PR checklist.
Don't simply tick the boxes like if you actually did what is written in it (ticking it also in the wrong way)
Screenshot 2024-07-12 at 2 39 59 PM

Marking as invalid and in need of work.

**Comment by anubhavd7** [comment]
please tell me which file i need to add or i need to edit in my file

**Comment by Cipulot** [comment]
Reading the documentation and the checklist will have all the answers.

**Comment by anubhavd7** [comment]
i have uploaded the files again please check it

**Comment by Cipulot** [comment]
.... you uploaded the entire QMK code, not the JSON for VIA.
There are some missing pieces of info on how to handle the PR. 

I suggest you read the docs again.

**Comment by anubhavd7** [comment]
sir i read it can you please edit it if possible. I am not able to get the mistakes i am making

**Comment by anubhavd7** [comment]
@Cipulot I HAVE UPLOADED THE JSON FILE FOR VIA AND I HAVE COMPARED IT WITH BINEPAD/PIXIE MY FILE IS SAME AS THEM.

**Comment by anubhavd7** [comment]
Screenshot (85)

**Comment by Cipulot** [comment]
- No need to full caps
- No need for pings
- A simple side-by-side shows that it's not true:
Screenshot 2024-07-12 at 3 13 09 PM

- You clearly didn't read the PR Checklist:
    - `the VIA support for this keyboard is MERGED in QMK master already (MANDATORY)`
        You ticked it as checked while not providing the QMK merge link.
    - `The VIA definition follows the guide here: etc`
      This is unticked, the simple fact that even one of the PR Checklist items isn't ticked is by default a cause of a PR not being approved from the get go.
    - `I have a V3 JSON version for this keyboard definition.(MANDATORY)`
      You ticked it as checked, yet you had `"lighting": "none",`, which is not a V3 version of the definitions.
    - `I have tested this keyboard definition using VIA's "Design" tab.`
       You ticked it as checked, yet a simple upload in the design tab shows that it doesn't work as a V3 json:
       
Screenshot 2024-07-12 at 3 08 31 PM
A direct cause of the lack of V3 formats mentioned earlier.
          
When the issues are addressed you can go on and open another PR.
Cheers.

**Comment by anubhavd7** [comment]
@Cipulot NO NEED FOR FULL CAPS MEANS SIR? CAPSLOCK SHOULD BE OFF IN THE NAME AND VENDOR ID?

**Comment by Cipulot** [comment]
`No need for full caps` means that it is NOT NECESSARY to reply to the PR comments in full caps.
Locking this PR as it is clear that issues are not understood and addressed.

**Pull request closed without merging**
