### PR TITLE
Added upcoming Midway60 Keyboard

### PR DESCRIPTION
**Pull request by mrnoisytiger**
## Description
Added upcoming Midway60 Keyboard

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/12747

## Checklist

- [x] The VIA support for this keyboard is in QMK master already (MANDATORY)
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by mrnoisytiger** [comment]
Any chance I could get review on this?

**Comment by wilba** [comment]
waiting for QMK PR to be merged

**Comment by mrnoisytiger** [comment]
Updated QMK pull reuqest to https://github.com/qmk/qmk_firmware/pull/12747

**Comment by mrnoisytiger** [comment]
@wilba Merged on QMK. Thanks!

**Pull request merged**
