### PR TITLE
Create sodium62.json

### PR DESCRIPTION
**Pull request by Na-Cly**
## Checklist

- [X] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [X] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [X] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [X] I have tested this keyboard definition using VIA's "Design" tab.
- [X] I have tested this keyboard definition with firmware on a device.
- [X] I have assigned alpha keys and modifier keys with the correct colors.
- [X] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Cipulot** [comment]
@Na-Cly 2 things:

- add QMK PR merge link as per requirements of the PR
- apply formatting to the json

**Comment by Na-Cly** [comment]
https://github.com/qmk/qmk_firmware/pull/23063
https://github.com/qmk/qmk_firmware/pull/17345

What formatting did you want in the json? It's formatted correctly in my vscode.

**Comment by Na-Cly** [comment]
Thank you.

**Comment by Na-Cly** [comment]
Is there anything outstanding for this?

**Comment by Na-Cly** [comment]
Can I get this merged?

**Review by Cipulot — APPROVED** [review]

**Pull request merged**
