### PR TITLE
feat: add ymdk split 64 keyboard

### PR DESCRIPTION
**Pull request by bbeesley**
Adds a working config for the YMDK Split 64 (aka sp64).

## Description

Adds a working config for the YMDK Split 64 (aka sp64).

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/16152

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by yiancar** [comment]
Hello! CI has failed, can you take a look please?

**Comment by bbeesley** [comment]
> Hello! CI has failed, can you take a look please?

OK, hopefully fixed. Is there a repo where the docs for the website are stored? The required props on the spec page don't include the required props for v3 support: https://www.caniusevia.com/docs/specification I'd like to open a PR to update that so that other people don't hit the same issue.

**Comment by yiancar** [comment]
Regarding V3 actually it is not fully implemented yet.
Docs will be updated and publicly available once both the qmk side and reader side are fully up to scratch!

**Comment by yiancar** [comment]
Cool the problem was not ur v3 change rather a missing ] :)
Anywho, your changes can stay 👍

**Pull request merged**
