### PR TITLE
Add support for MNK65

### PR DESCRIPTION
**Pull request by kopibeng**
## Description
Add support for MNK65

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/16400

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by yiancar** [comment]
Hello!
CI had broken you will need to rebase from master:
```
git fetch upstream
git rebase upstream/master
git push (might have to force)
```

**Comment by kopibeng** [comment]
Thank you so much!

**Comment by yiancar** [comment]
Hello! again can you keep only your own JSON.
Cheers.

**Comment by kopibeng** [comment]
Sorry, all done!

**Comment by yiancar** [comment]
Same as the other commit please. make sure that inf the diff there is only the addition of your json

**Pull request merged**
