### PR TITLE
Add the Abats Keyboard Club Nayeon

### PR DESCRIPTION
**Pull request by ramonimbao**
## Description

Adds the Abats Keyboard Club Nayeon keyboard.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/16659

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by ramonimbao** [comment]
Hey @Xelus22, how would I go about with this? The conflicting keyboard is the Keygem KG60 (https://github.com/the-via/keyboards/pull/1303) but checking the PR for it, it hasn't been merged to QMK yet (https://github.com/qmk/qmk_firmware/pull/17565).

**Comment by Xelus22** [comment]
The automatic build says it is failing. So please fix any errors.

**Comment by ramonimbao** [comment]
The error is that the Keygem K60 conflicts with the Nayeon, but the Keygem K60 isn't merged yet with QMK despite being merged with VIA.

**Comment by wilba** [comment]
I did merge the Keygem boards into VIA before they were in QMK master.

That did not throw an error because the Nayeon VID/PID was not in VIA yet, so there was no conflict.

This is the first time we've had to deal with such a conflict, and it's a bit complicate.

@mrnoisytiger could have checked the VID/PID was unique (in QMK) before their PR to QMK and VIA

However, it is using ASCII codes "KG" for the VID (i.e. **K**ey**g**em) and there's no obvious reason why "Abats Keyboard Club Nayeon" would be using "KG".

@ramonimbao @mrnoisytiger Can you give more information about this, and have a discussion here please?

I'd like a solution that is the *least inconvenient* to the people owning the PCBs, and least disruptive to both of you.

**Comment by ramonimbao** [comment]
The `4B47` is just very loosely based on *Abat*s. I am alright with changing the VID/PID in QMK and then updating it here. I have some VIAL firmware prepared for the Nayeon since the boards use RP2040 and were made before the latest breaking change.

**Comment by Xelus22** [comment]
I guess you could just use ABA7?

**Comment by mrnoisytiger** [comment]
I chose 4B47 specifically because of a client request to use the KG hexcodes for KeyGem. Unfortunately we already have **many** boards produced with this firmware and they are already in market (with multiple variants too, basically copying all the DZ__ variants). I think like Xelus suggested to use `ABA7` would be the least breaking and would probably align with *Abats* better?

**Comment by ramonimbao** [comment]
Alright, will go with `ABA7`. Thanks.

**Comment by ramonimbao** [comment]
Well that was quick. The new VID has been merged into QMK. Thanks everyone!

**Comment by wilba** [comment]
ggwp

**Pull request merged**
