### PR TITLE
Add nullbits NIBBLE keyboard

### PR DESCRIPTION
**Pull request by jaygreco**
## Description

Add support for nullbits NIBBLE keyboard

## QMK Pull Request
https://github.com/qmk/qmk_firmware/pull/9250

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by jaygreco** [comment]
any update?

**Comment by Wilba6582** [comment]
Waiting on QMK PR merge

**Comment by jaygreco** [comment]
QMK merge in progress

**Comment by jaygreco** [comment]
Removed the encoder from custom modes, as it was only confusing users.

**Pull request merged**
