### PR TITLE
added support for Bobpad

### PR DESCRIPTION
**Pull request by AnanyaKirti**
added support for Bobpad

## Description

added support for Bobpad

## QMK Pull Request 
Already merged with QMK
https://github.com/qmk/qmk_firmware/pull/13989

https://github.com/qmk/qmk_firmware/pull/13989

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Xelus22** [comment]
Hi please fix the CI error. It shouldn't be in the `src/` folder it should be under the `v3` folder

**Comment by AnanyaKirti** [comment]
hey! I have moved bobbed to V3

**Review by Xelus22 — CHANGES_REQUESTED** [review]
Please rename the folder to mirror the tree in qmk.

`v3/bobpad/bobpad.json`

**Comment by AnanyaKirti** [comment]
done!

**Comment by AnanyaKirti** [comment]
I'm lost, can you verify this work? where do I have to put my json file? in v/bobpad/bobpad.json or v3/Desiboards/bobpad.json. thanks!

**Comment by Xelus22** [comment]
as `v3/bobpad/bobpad.json`

**Comment by Xelus22** [comment]
Looks like you've accidentally touched some other files in here as well.

**Comment by AnanyaKirti** [comment]
closing this and creating a new pull request

**Pull request closed without merging**
