### PR TITLE
Added ek87 support

### PR DESCRIPTION
**Pull request by eniigmakeyboards**
## Description
Added support for the ek87 PCB, designed for Eniigma Keyboards TKL products.

## QMK Pull Request 
[Here](https://github.com/qmk/qmk_firmware/pull/9087)

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by eniigmakeyboards** [comment]
The QMK PR has now been merged.

**Comment by eniigmakeyboards** [comment]
PR has been merged.

**Comment by eniigmakeyboards** [comment]
Issue found: only "basic" key remapping works, other keys don't work. They show up in the UI but don't actually work.

**Comment by Wilba6582** [comment]
will wait until media keys is fixed. please add another QMK PR link

**Comment by eniigmakeyboards** [comment]
Here is the new link to the QMK PR: https://github.com/qmk/qmk_firmware/pull/9087

Also updated in OP

**Comment by eniigmakeyboards** [comment]
QMK PR has been merged.

**Pull request merged**
