### PR TITLE
Add nullbits SNAP keyboard

### PR DESCRIPTION
**Pull request by jaygreco**
## Description

Add the nullbits SNAP keyboard.

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/18916

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by jaygreco** [comment]
Hi @yiancar! The QMK PR (#18916) was FINALLY merged. Do you mind opening this again? Do you know if there have been any breaking changes to the VIA schema in the few months that have passed that I'll need to address?

**Comment by yiancar** [comment]
Hello, Yes you will need to create a v3 json as well. please check the docs:)

**Comment by jaygreco** [comment]
> Hello, Yes you will need to create a v3 json as well. please check the docs:)

Thanks for the heads up -- done!

**Comment by jaygreco** [comment]
> Hello, Yes you will need to create a v3 json as well. please check the docs:)

Thanks for the heads up @yiancar. Done!

**Comment by jaygreco** [comment]
Hi @yiancar, can this be merged? Thanks, and apologies for the ping.

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
