### PR TITLE
added heliotrope support to via (new KB)

### PR DESCRIPTION
**Pull request by MATTMCCA**
## Description

Adding heliotrope support to via.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/19296

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by MATTMCCA** [comment]
On the record, who ever reviews these pull requests. I see you, you are a real person, and "I" appreciate all of the time and effort you put into to supporting this project. without folks like you, this via would be nothing. I just wanted to say thanks, its something people don't hear enough.

**Comment by yiancar** [comment]
Hello there,
Thank you for the nice words! Could you please fix the failing CI?:)

**Comment by MATTMCCA** [comment]
I removed the spaces, however I fear this may not fix the failing CI, could you give me a little more detail as to what the issue is? Any advice is greatly appreciated. Thank you.

**Comment by yiancar** [comment]
Passes now and can confirm the rest. Cheers:)

**Pull request merged**
