### PR TITLE
Created via design for djinn

### PR DESCRIPTION
**Pull request by nilestanner**
## Description

Adding design for Djinn, includes encoders and 5 way switches

djinn-via

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/19881

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by nilestanner** [comment]
@yiancar looks like the qmk change had not been merged. Is that an issue?

**Comment by yiancar** [comment]
Yes it is part of the checklist... I am sorry I will have to revert the merge until it is done so

**Comment by yiancar** [comment]
Please let me know once it is merged in qmk

**Comment by nilestanner** [comment]
@yiancar the qmk PR is merged should I reopen this one?

**Comment by yiancar** [comment]
@nilestanner yes please can you just recreate the PR

Cheers

**Comment by nilestanner** [comment]
recreated here https://github.com/the-via/keyboards/pull/1739 @yiancar

**Pull request merged**
