### PR TITLE
Create bm60v2_ec.json

### PR DESCRIPTION
**Pull request by elffyb**
## Description

This creates a json for the BM60 EC Version 2

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by yiancar** [comment]
Hello Please provide the QMK pull request link so we can verify it has already been merged.
I will reopen the PR once that has been provided.

**Comment by elffyb** [comment]
https://github.com/qmk/qmk_firmware/tree/master/keyboards/kprepublic/bm60hsrgb_ec


Thanks,Brett
    On Sunday, August 7, 2022 at 04:52:27 PM CDT, yiancar ***@***.***> wrote:  
 
 


Hello Please provide the QMK pull request link so we can verify it has already been merged.
I will reopen the PR once that has been provided.

**Comment by yiancar** [comment]
Cheers thanks!

**Comment by elffyb** [comment]
Thanks for the speedy delivery!
Brett
    On Monday, August 8, 2022 at 05:09:11 PM CDT, yiancar ***@***.***> wrote:  
 
 


Merged #1347 into master.

**Pull request merged**
