### PR TITLE
create rk839us.json

### PR DESCRIPTION
**Pull request by sdk66**
create rk839us.json，frist commit

## Checklist

- [ ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Cipulot** [comment]
@sdk66 not sure if you wanted to push on your fork....
If the intention was to have the board merged in the main repo then I suggest you to read the PR Checklist carefully and get back to this.

**Comment by sdk66** [comment]
> 不确定你是否想推你的叉子......如果打算将董事会合并到主存储库中，那么我建议您仔细阅读 PR 清单并返回此主题。



> @sdk66 not sure if you wanted to push on your fork.... If the intention was to have the board merged in the main repo then I suggest you to read the PR Checklist carefully and get back to this.

I'm now trying to merge my json file into the repository, thank you for your comments, I'll try again to read the docs and upload them

**Comment by Cipulot** [comment]
the PR still has issues. First with the PR checklist not being followed...
Furthermore, there's no match between the naming of what you are trying to merge...

- PR Title: rk839us
- json file name: rk839.json
- board name within the file: RK-R65

Like.... what are you even trying to merge at this point.

**Comment by Cipulot** [comment]
https://github.com/qmk/qmk_firmware/issues/24085

**Pull request closed without merging**
