### PR TITLE
Add Stream Cheap 2x4

### PR DESCRIPTION
**Pull request by mpfl**
## Description

Add the Stream Cheap - a handwired 2x4 macro pad

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/14001

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by wilba** [comment]
There is no link to the merged PR which shows that VIA support for this keyboard is in QMK master already.

**Comment by mpfl** [comment]
I'm sorry, but this PR was still in draft, pending the merge into QMK.

**Comment by mpfl** [comment]
https://github.com/qmk/qmk_firmware/pull/14001 has now been merged. I would appreciate it if you could restore this pull request to draft.

**Comment by mpfl** [comment]
Many thanks.

**Pull request merged**
