### PR TITLE
Add MxSS

### PR DESCRIPTION
**Pull request by MxBlu**
## Description

Add MxSS config to VIA

QMK PR: https://github.com/qmk/qmk_firmware/pull/7809

## Types of Changes

- [x] Adding a keyboard to VIA
- [ ] Changing a keyboard already in VIA
- [ ] Bug fix
- [ ] Documentation

## Checklist

- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] The QMK firmware can be built using QMK master repo.

### CODE REVIEW

**Comment by Wilba6582** [comment]
Looks OK, will merge after QMK PR is merged.

**Comment by MxBlu** [comment]
RGB support now in, was going to wait for QMK merge of the initial set first but thought it wasn't really worth the wait.

**Comment by MxBlu** [comment]
Aaand reverted.

**Comment by MxBlu** [comment]
It is done. I'll swap over the backlight mode to rgblight along with adding the advance config code in, which ill do in a new PR if that's alright.

**Pull request merged**
