### PR TITLE
Add some Keychron wireless keyboards v2 json

### PR DESCRIPTION
**Pull request by lokher**
## Description

Add part of keychron wireless keyboard V2 json:

 K2 Pro:  iso_white / iso_rgb / ansi_white / ansi_rgb
 K3 Pro:  iso_white / iso_rgb / ansi_white / ansi_rgb
 K4 Pro:  iso_white / iso_rgb / ansi_white / ansi_rgb
 K6 Pro:  iso_white / iso_rgb / ansi_white / ansi_rgb / jis_rgb
 K7 Pro:  ansi_white / ansi_rgb
 K8 Pro:  iso_white / iso_rgb / ansi_white / ansi_rgb / jis_white / jis_rgb
 K10 Pro:  ansi_white / ansi_rgb
 Q1 Pro: iso_rgb_knob / ansi_rgb_knob

## Checklist

- [ ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [ ] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by wilba** [comment]
https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron

@Xelus22 @yiancar can you sanity check against the source code

**Comment by zacuke** [comment]
The K10 Pro keyboard seems to have missed being added to QMK master

**Comment by hloeung** [comment]
> All the The K series keyboards seem to have missed being added to QMK master

Mentioned here too - https://github.com/qmk/qmk_firmware/issues/24085#issuecomment-2295226113

**Comment by PeterMortensen** [comment]
> All the The K series keyboards seem to have missed being added to QMK master

They don't use QMK; they have proprietary firmware (unless [going exotic](https://www.reddit.com/r/olkb/comments/1avk4g3/comment/krigncf/)).

**Pull request merged**
