### PR TITLE
Add Via support for Absinthe

### PR DESCRIPTION
**Pull request by alittlepeace**
Adding Via Support

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/13031

## Checklist

- [x] The VIA support for this keyboard is in QMK master already (MANDATORY)
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by wilba** [comment]
needs QMK PR

**Comment by alittlepeace** [comment]
> needs QMK PR

Oop, sorry. Didn't notice the PR was only approved by one person and wasn't completed.

**Comment by alittlepeace** [comment]
Keymap merged into QMK main branch 

> needs QMK PR

**Comment by wilba** [comment]
still needs a link to the QMK PR

**Comment by alittlepeace** [comment]
> still needs a link to the QMK PR

fixed

**Pull request merged**
