### PR TITLE
add ppr_merro60

### PR DESCRIPTION
**Pull request by gaclee3b**
## Description

Adding new 60% PCB.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/23014

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by gaclee3b** [comment]
the build looks like it's failing because it's expecting "v2" format (specifically requiring the "lighting" property), but "v3" is required. Did I configure something incorrectly or is this a bug in the checker?

**Comment by gaclee3b** [comment]
Looks good after moving my files from "src" to "v3". Can someone help me review and approve?

**Review by dunk2k — CHANGES_REQUESTED** [review]
1. add WKL and HHKB bottom row options (inherent variants of Tsangan)
2. moved 2.75u Right shift and 2u Backspace to align with ISO Enter
3. moved `"y": 0.25` from 3rd bottom row to 2nd bottom row

**Review by Xelus22 — CHANGES_REQUESTED** [review]
image

Should this be grey?

**Comment by gaclee3b** [comment]
hello, i think i've covered the requested changes a few weeks ago and don't have any other changes planned. could someone check and approve?

**Review by Xelus22 — CHANGES_REQUESTED** [review]
Hey sorry for the long delay, been quite busy. Just one last thing you will need `decals` in the empty spots on the bottom rows 

https://www.caniusevia.com/docs/layouts#layout-options

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
