### PR TITLE
Nico update

### PR DESCRIPTION
**Pull request by yulei**
added HHKB layout for this keyboard

## Checklist

- [x ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x ] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [ x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [ x] I have tested this keyboard definition using VIA's "Design" tab.
- [x ] I have tested this keyboard definition with firmware on a device.
- [ x] I have assigned alpha keys and modifier keys with the correct colors.
- [ x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Xelus22** [comment]
Please add QMK PR

**Comment by yulei** [comment]
> Please add QMK PR

https://github.com/qmk/qmk_firmware/pull/22027

**Review by Xelus22 — CHANGES_REQUESTED** [review]
Merge issue

**Comment by yulei** [comment]
> Merge issue

fixed

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
