### PR TITLE
Add support for era/divine

### PR DESCRIPTION
**Pull request by eerraa**
## Description
Add support for era/divine

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/21593

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Xelus22** [comment]
Please paste in QMK PR

**Comment by eerraa** [comment]
> Please paste in QMK PR

Thank you sir, I forgot about it for a while.

**Review by Xelus22 — CHANGES_REQUESTED** [review]
Please remove v2 definition (src/ folder) as that is only for legacy boards.

**Comment by eerraa** [comment]
> Please remove v2 definition (src/ folder) as that is only for legacy boards. Everything else looks good.

@Xelus22 Thank you., I've done as you requested.

**Review by Xelus22 — APPROVED** [review]

**Comment by eerraa** [comment]
@Xelus22 
Hi there,
I'm using both Vial and Via.
If the board's v2 definition is missing, newer Vial-based firmware will throw a "fetching v2 definition failed" error and VIA will not work.
Could you please allow me to merge the v2 definition?

**Pull request merged**
