### PR TITLE
Add support for OwLab Suit80

### PR DESCRIPTION
**Pull request by owlab-git**
## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by owlab-git** [comment]
bump

**Comment by kb-elmo** [comment]
There is nothing to bump here.

The QMK PR for this keyboard is not yet merged into master.
Which you failed to link in the PR (which is btw very clearly listed as a requirement in the template).
https://github.com/qmk/qmk_firmware/pull/14362 

You apparently even failed to properly read what the template says.

> The VIA support for this keyboard is in QMK master already (MANDATORY)

This MANDATORY is not there as a joke.
You marked this off as complete even though it isn't

**Comment by kb-elmo** [comment]
> Updated definitions with colors per VIA's KLE JSON rules, see this gist. Nice board!

The files in that gist aren't correct either...

**Comment by owlab-git** [comment]
Modified

**Comment by kb-elmo** [comment]
ISO layout file is still wrong...

**Comment by gknapp** [comment]
Thanks for the feedback. It'd help if you could add a short note why, so we don't duplicate effort - you find the mistake, then I try to find the mistake.

**Comment by kb-elmo** [comment]
> Thanks for the feedback. It'd help if you could add a short note why, so we don't duplicate effort - you find the mistake, then I try to find the mistake.

I'm talking directly with the Owlab guys on Discord (I worked with them before).
That's why I didn't add the fixed jsons here.

There are also plenty of other TKLs in this repo that you can use as a reference how a correct json should look like.

For the ISO version the correct layout would look like this
preview

**Comment by owlab-git** [comment]
ISO file modified.

**Comment by wilba** [comment]
@kb-elmo do I merge or not?

**Comment by kb-elmo** [comment]
> @kb-elmo do I merge or not?

Yeah looks fine I think 😄

**Pull request merged**
