### PR TITLE
Added Rooboard65

### PR DESCRIPTION
**Pull request by mrnoisytiger**
## Description

Added Rooboard65

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/15044

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by mrnoisytiger** [comment]
@wilba why was this PR closed?

**Comment by wilba** [comment]
QMK PR is closed

**Comment by mrnoisytiger** [comment]
> QMK PR is closed

Ah whoops my bad. It appears I forgot to update the QMK PR link. https://github.com/qmk/qmk_firmware/pull/15294

**Comment by mrnoisytiger** [comment]
Bump?

**Comment by mrnoisytiger** [comment]
Bump.

**Pull request merged**
