### PR TITLE
Update maypad.json to Correctly Reflect Device ID

### PR DESCRIPTION
**Pull request by dot-hex**
## Description

The device ID was changed in the QMK PR, but was not changed in the original VIA port branch. This PR resolves that error and allows VIA to recognize the QMK compiled firmware. This is an update to the Maypad.json file.

## Checklist

- [X] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [X] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [X] I have tested this keyboard definition using VIA's "Design" tab.
- [X] I have tested this keyboard definition with firmware on a device.
- [] I have assigned alpha keys and modifier keys with the correct colors.
- [X] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by dot-hex** [comment]
I'm unsure as to why it claims the whole file has been changed: the only change is the change of the device ID to reflect what is in QMK, which is 0x4D50

**Comment by Wilba6582** [comment]
This is what I am seeing in KLE: 

image

Can you please fix this?

**Comment by dot-hex** [comment]
Sorry! I missed some formatting that needed to be removed for the JSON to display properly. This is what I see with the updated json that I just pushed to the branch.

image

**Comment by Wilba6582** [comment]
I don't know what's up with this merge. Can you update your master branch, then make a new branch and submit again please?

**Comment by dot-hex** [comment]
I have updated my master branch, created a new branch, and submitted the PR [here](https://github.com/the-via/keyboards/pull/261). I am closing this PR to reduce clutter.

**Pull request closed without merging**
