### PR TITLE
Add MelGeek MJ6xy which is a 60% keyboard and support multi-layouts

### PR DESCRIPTION
**Pull request by mj-bomb**
## Checklist

- [x] The VIA support for this keyboard is in QMK master already (MANDATORY)
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by mj-bomb** [comment]
@wilba @yiancar  @Conor-Burns   @ Hello,Please approve,thank you very muck!

**Comment by wilba** [comment]
needs QMK PR link

**Comment by mj-bomb** [comment]
> needs QMK PR link
here is the pr link, I think it will be merged in a while.

https://github.com/qmk/qmk_firmware/pull/13494

**Comment by mj-bomb** [comment]
@yiancar @Conor-Burns    Hello,Please help to check it,thank you very muck!

**Comment by Conor-Burns** [comment]
Heyo @mj-bomb 
Just a heads up: I'm not a a collaborator on this repo😅

But hey it looks nice from my understanding 😂

**Comment by mj-bomb** [comment]
> needs QMK PR link
hello. it's mergerd by qmk. please check it. Thank you very much.
the pr link is https://github.com/qmk/qmk_firmware/pull/13494

**Pull request merged**
