### PR TITLE
Add Maartenwut Wasdat

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

image

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/8762

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Wilba6582** [comment]
The KLE is missing some mod colors

The "no numpad" layout option group (keys with decal state on) don't need matrix coordinates in the labels.

**Comment by fauxpark** [comment]
I've just set Caps Lock as a modifier. I don't consider Tab, Backslash or Backspace to be part of that group.

Good to know about the decal keys.

**Comment by Wilba6582** [comment]
I use the term "modifier" loosely, to mean all keys that are colored the same in a standard keycap set.

Example: https://cdn.shopify.com/s/files/1/3099/8088/products/R_500_2018-03-23_1024x1024@2x.png?v=1522284466

**Comment by fauxpark** [comment]
image
Looks like this now. Would be nice if the modifier keys were coloured differently to the normal keys, and perhaps a nomenclature change from "modifier" to "secondary" or something. That's why I thought it might actually be for "proper" modifiers.

**Comment by Wilba6582** [comment]
Yeah, they used to, before @olivia switched to GMK Olivia++ Dark theme

**Comment by Wilba6582** [comment]
We will have configurable themes one day, I just need to keep nagging....

**Pull request merged**
