### PR TITLE
Enable Via for the Sofle

### PR DESCRIPTION
**Pull request by Sturek**
## Description

Created a mapping for the Sofle. Includes underglow support.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/10446

## Checklist

- [X] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [X] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [X] I have tested this keyboard definition using VIA's "Design" tab.
- [X] I have tested this keyboard definition with firmware on a device.
- [X] I have assigned alpha keys and modifier keys with the correct colors.
- [X] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Sturek** [comment]
The changes in QMK have been merged.

**Review by 2Moons-JP — COMMENTED** [review]
It looks the right hand may be backwards when compared to the QMK .h file and the Keymap. Does it work on hardware ok? If so disregard. 5,5 here is R00 in QMK not R05.

**Comment by Sturek** [comment]
I will double check, but I have been using this JSON with the hardware and it works fine. My guess is that this has to do with the fact that the PCB is reversible?

**Comment by Sturek** [comment]
Yeah, it works fine and the matrix test also shows everything correctly.

**Comment by fsargent** [comment]
Not sure if something's changed but the layout is a bit different for my sofle. Play/Mute are the encoders in the image. The left thumb row is shifted over by one. I can't really understand how to fix it, is there a tool, or is it done just by json array modification?
image

**Comment by Sturek** [comment]
I am not sure I can follow. If your Sofle looks different and the keys in VIA don't fit the physical layout, you may have the v2 version of the Sofle. This is for the v1.

**Pull request merged**
