### PR TITLE
adding jabberwocky v2 keyboard

### PR DESCRIPTION
**Pull request by lukeski14**
## Description
Adding jabberwocky v2 .json
Reorganizing /jabberwocky/ directory, since v1 already is ported to via

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/19014

Update to productId PR open here: https://github.com/qmk/qmk_firmware/pull/19611

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by lukeski14** [comment]
Should probably change product ids. Going to address this

**Comment by lukeski14** [comment]
Updated productId QMK PR here: https://github.com/qmk/qmk_firmware/pull/19611

**Comment by yiancar** [comment]
please ping once the merge of qmk has been done.

**Comment by lukeski14** [comment]
@yiancar QMK PR merged

**Comment by yiancar** [comment]
Hello you have added V1 and V2 here. they both have the same PID/VID, this is not allowed. I presume there is a different firmware in V1 and V2?
Also if the JSON are the same you can just add one...

**Comment by lukeski14** [comment]
The firmware for v1 and v2 is different. I explicitly changed the pid for v2 so now each version has a unique pid. This is the change merged in the most recent QMK PR.

**Comment by yiancar** [comment]
Ok I see, however in the V1 and V2 JSONS on this PR, both have     
```
"vendorId": "0x4E50",
 "productId": "0x4A58",
```

**Comment by lukeski14** [comment]
In this PR, I added v1 and v2 folders.

These are the productIds for each version as seen in this PR:
v1 productId: "0x4A57"
v2 productId: "0x4A58"

From what I can see, the v1 and v2 productIds are correct. The v1 json already existed so the only change in this PR is a file path change for v1. v2 has the new productId, different from v1.

**Comment by yiancar** [comment]
sorry I am blind.... I couldnt see the right diff....

cheers and thanks for clarifying

**Pull request merged**
