### PR TITLE
Doro67

### PR DESCRIPTION
**Pull request by mechmerlin**
## Description

Add in VIA support for the Doro67 Regular and RGB versions. There is VIA firmware built for the multi layout VIA, but I have not been able to find someone who can confirm that it actually works. 

## Types of Changes

- [x] Adding a keyboard to VIA
- [ ] Changing a keyboard already in VIA
- [ ] Bug fix
- [ ] Documentation

## Checklist

- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] The QMK firmware can be built using QMK master repo.

### CODE REVIEW

**Comment by Wilba6582** [comment]
These have an alpha colored Left Win key.

Also can you add the definition for the "multi" PCB since you added this to QMK as well.

**Comment by Wilba6582** [comment]
bump

**Comment by Wilba6582** [comment]
@mechmerlin bump

**Comment by mechmerlin** [comment]
Still looking for someone to test the multi

**Comment by Wilba6582** [comment]
Can't you just define it to match the QMK and commit it anyway?

**Comment by mechmerlin** [comment]
> Can't you just define it to match the QMK and commit it anyway?

One of your checkboxes is testing of the board, so if you're cool with me not testing it I can just commit it.

**Comment by mechmerlin** [comment]
Done!

**Pull request merged**
