### PR TITLE
Add two new keyboards and move romac to personal subfolder

### PR DESCRIPTION
**Pull request by The-Royal**
## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by TheRoyalSweatshirt** [comment]
"Liminal" and "Romac+" are both also pending a PR I'm submitting right now to add via keymap to QMK:master.

**Comment by The-Royal** [comment]
Romac Keymap Merged. 

Now Just waiting on Liminal PR to get it's 2nd Approval before merge.

**Comment by Wilba6582** [comment]
https://github.com/qmk/qmk_firmware/pull/8965

**Comment by The-Royal** [comment]
@Wilba6582 All QMK PRs merged and closed 👍

**Pull request merged**
