### PR TITLE
Add support for 1up60hse (already in QMK)

### PR DESCRIPTION
**Pull request by stanrc85**
Adding support on VIA side for 1up60hse keyboard, already supported on QMK side (https://github.com/qmk/qmk_firmware/pull/7992).

## Types of Changes

- [x] Adding a keyboard to VIA
- [ ] Changing a keyboard already in VIA
- [ ] Bug fix
- [ ] Documentation

## Checklist

- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] The QMK firmware can be built using QMK master repo.

### CODE REVIEW

**Comment by Wilba6582** [comment]
Please update the colors to be consistent with the others, using #cccccc #aaaaaa #888888 and #000000 for legends.

Legend for matrix coord on spacebar should be top left.

Lighting should be `qmk_backlight_rgblight` since PCB supports both.

**Comment by stanrc85** [comment]
> Please update the colors to be consistent with the others, using #cccccc #aaaaaa #888888 and #000000 for legends.
> 
> Legend for matrix coord on spacebar should be top left.
> 
> Lighting should be `qmk_backlight_rgblight` since PCB supports both.

Removed colors, fixed backlight options, and corrected some layout mistakes

**Comment by Wilba6582** [comment]
I meant you can use #aaaaaa for mods and #888888 for accents.

Spacebar coord is still not top left.

**Comment by stanrc85** [comment]
Can you point me to example or reference for the spacebar coord? I'm not familiar with that. 

I wasn't worried about the colors, they were just in the file I copied code from to get started.

**Comment by Wilba6582** [comment]
The spacebar has the switch matrix coordinate in the center label instead of the top left label.

**Comment by stanrc85** [comment]
I understand what you want but I don't know how to make that happen. I can't find anything in the docs that demonstrate it and I can't find an example to follow in any of the other VIA keyboard json files.

**Comment by Wilba6582** [comment]
I don't even know why you are doing this, when you didn't even do the QMK port.

**Comment by Wilba6582** [comment]
Duplicate of #36

**Comment by stanrc85** [comment]
Thanks!

**Pull request closed without merging**
