### PR TITLE
Add VIA support for Keychron C2 Pro

### PR DESCRIPTION
**Pull request by lalalademaxiya1**
Added VIA JSONs for Keychron C2 Pro and request for a review, Thanks!

## Description

- Added c2_pro/c2_pro_ansi_rgb.json to v3/keychron
- Added c2_pro/c2_pro_ansi_white.json to v3/keychron
## QMK Pull Request 

qmk/qmk_firmware#20701

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by asmbk** [comment]
These definitions don't work for me. Please look for my [fix](https://github.com/Keychron/keyboards/compare/keychron-c2_pro...asmbk:keyboards:keychron-c2_pro)

**Comment by Xelus22** [comment]
@lalalademaxiya1 ^

**Comment by lalalademaxiya1** [comment]
@asmbk Hi, after comparison, there are indeed errors in the this file, corrected it now, Thanks!

**Comment by lalalademaxiya1** [comment]
@Xelus22 Hi, corrected it. Thanks!

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
