### PR TITLE
Add VIA support for Tinyneko/Eclipse60

### PR DESCRIPTION
**Pull request by MaiTheSan**
## Description
Add support for eclipse60/tinyneko

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/19379

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by yiancar** [comment]
Can you please add V3 Jsons as well?

**Comment by MaiTheSan** [comment]
> Can you please add V3 Jsons as well?

yes

**Comment by yiancar** [comment]
Cheers thanks!

**Comment by MaiTheSan** [comment]
thanks~

**Pull request merged**
