### PR TITLE
Create KK65.json

### PR DESCRIPTION
**Pull request by apricity-spam**
Added KK65.json to keyboards.

## Description
Added KK65.json to keyboards for my limited run keyboard.

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/22772

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Review by Xelus22 — APPROVED** [review]

**Review by Xelus22 — CHANGES_REQUESTED** [review]
image

looks like someone else already uses the same VID/PID.

**Comment by apricity-spam** [comment]
I updated the VID to remove the conflict. I have submitted a pull request with the QMK repository to change the VID as well.

**Comment by Xelus22** [comment]
> I updated the VID to remove the conflict. I have submitted a pull request with the QMK repository to change the VID as well.

Thanks. Could you also link that QMK PR?

**Comment by apricity-spam** [comment]
QMK PR Link: https://github.com/qmk/qmk_firmware/pull/23007

**Comment by apricity-spam** [comment]
QMK PR has been merged

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
