### PR TITLE
Add support for Keychron k1 pro

### PR DESCRIPTION
**Pull request by KeychronMacro**
Added VIA support for Keychron k1_pro and request for reviews, Thanks!

## Description

- Added VIA JSONs for Keychron k1_pro.

  - Added ansi_rgb / ansi_white.
  - Added JSONs to src and v3.

## Checklist

- [ ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by mnasyrov** [comment]
Hello! What is the status of this PR: in progress or abandoned? What is the timeframe for completing this PR?

**Comment by kdashg** [comment]
As an outsider, the apparent state is:
* This PR appears to be blocked on this requirement: "The VIA support for this keyboard is MERGED in QMK master already (MANDATORY)"
* There does not appear to be any PR against `qmk/qmk_firmware` for the k1 pro yet: https://github.com/qmk/qmk_firmware/pulls?q=is%3Apr+k1+pro
* `k1_pro` support is only present in the (experimental?) `bluetooth_playground` branch of `Keychron`'s fork of `qmk/qmk_firmware`: https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron/k1_pro

So it seems like we're waiting for Keychron (or anyone else?) to PR support for the k1 pro into `qmk/qmk_firmware/master`.

I am looking at mugging `Keychron/qmk_firmware/bluetooth_playground` and stitching together that PR in order to unblock this, but I'm not excited to try to do all the testing for it.

**Comment by thany** [comment]
Why is this step mandatory? Why is it so adament that there is firmware (?) support for this keyboard, even though it's functionally not neccesary for VIA to work with this keyboard?

This is wasting time. Please approve if okay, or make changes if not okay.

A PR for one repo shouldn't rely on a totally different repo.

**Comment by thany** [comment]
What does QMK have to do with VIA? Why does it need to support this keyboard? Can someone explain please?

If not, then please accept this PR already. It's been open for more than a year. This is only frustrating users owning a K1, not helping anyone.

If I load in the JSON on the design tab, it works perfectly fine. Why does it need anything more than that, in a repo that, again, is totally separate from this one?

**Comment by thany** [comment]
Okay. I don't care if the firmware is not available, and the corresponding keyboard can still be supported. This requirement is stupid and should be optional. It's an arbitrary requirement, it's only there because someone thought it should be.

As a user, I just want things to work. Not having the firmware available from the same tool where I remap keys, to me as a user, is trivial at best (meaning I couldn't give two tosses).

**Comment by yiancar** [comment]
@thany Thanks for the feedback. We will not change our rules. A bit of personal advice, when something is free try not to be rude or act privileged against the people who provide it.

**Comment by Cipulot** [comment]
@thany first of all, rude. The comment section of a PR isn't the local town plaza where people share the more or less and throw judgments w/o proper knowledge on the matter.

> I don't care if the firmware is not available

That's on you and your lack of knowledge about licensing compliance, not on the maintainers or other developers who diligently oblige by that. The original code for the board firmware is QMK-based, which is licensed under GPL V2/3, which explicitly states requirements and standards for code usage and publication.

> It's an arbitrary requirement, it's only there because someone thought it should be.

It is not, you might consider it like so, even a bit of a stretch, but the reasoning behind the requirement, as @yiancar outlined, is so that we, being maintainers or simply passionate users that provide help at their own free time expense, can help people out. W/o it the work is difficult and, to be honest, neither the maintainers nor the users are here to give free labor for the Keychron or YMBK or whoever else because they lack the most basic codebase practices. 
A clear example is the Discord Server for VIA, which ever since it was opened became the de-facto Keychron support page for anything that a Keychron board was not doing "as expected", the same for other Chinese manufacturers' boards off of Alixpress and similar.

> As a user, I just want things to work. Not having the firmware available from the same tool where I remap keys, to me as a user, is trivial at best (meaning I couldn't give two tosses).

This has nothing to do with the requirements or the maintainers, and all with the keyboard manufacturers not complying with licensing rules, codebase practices, and requirements.

Free to have your own opinion in terms of how much a thing is "stupid" or "couldn't give two tosses" but maybe before starting a rant in the comment section of a PR it would be better for the next time to inform yourself on the dynamics and requirements of the OS projects involved and who is actually to point fingers to when it comes to the user experience.

Finally, ever since the V3 update of VIA, you can now upload the json file, which is provided by Keychron [here (K1 Pro ANSI white backlight keymap JSON file)](https://cdn.shopify.com/s/files/1/0059/0630/1017/files/k1_pro_us_white_v1.00.json.zip?v=1677739753) and [here (K1 Pro ANSI RGB keymap JSON file)](https://cdn.shopify.com/s/files/1/0059/0630/1017/files/k1_pro_us_rgb_v1.10.json.zip?v=1677739753), once and never have to upload it at each session (as it was before the V3 update). This measure was implemented to try to meet the average user demands while not actively encouraging licensing terms breaking by not enforcing the PR merge requirements or allowing "whoever" to merge stuff w/o codebases being public.

**Comment by Cipulot** [comment]
@thany 
> Rude was intentional. This PR has been open for a year because of an arbitrary requirement. That's what I call rude - towards users who just want to use this software as intended.

As other keyboard manufacturers, hobbyists, or random users did, so Keychron & co can do. It is not for the maintainers to bend rules that 99% of the contributors followed to please some company that doesn't manage to make code that can be merged, it's the opposite. 
Also, your reiterating the intentionality of the tone in the replies doesn't help.

> Afaik, GPL only states that source code must be available. It doesn't require source code to be merged into some existing project.

It is an expected step because nothing prevents any random maintainer from pulling the code offline after some time, breaching the licensing. The merge in QMK itself is a "safe" way of ensuring that the license if perpetually followed and not only for the week or so needed for others to look at it, see it complied to then pull it offline.

> I don't see how having the firmware aids in doing so. I imagine many keyboards don't even have any updates, so you can just use the keyboard as it rolls off the assembly line.

That's on you. Firmware has bugs, some not directly dependent on the maintainer, like ChiboOS bugs that, w/o source code, cannot be addressed. Simple stuff like "my caps lock works in reverse" or other stuff requires the users to have access to it. The lack of "updates" or whatever is not something that should be used as the threshold of code being public or not.

> Fine, but don't inconvenience people by withholding a PR that helps those people in using your software. I can't help that I have a Keychron. I'm not going to buy another keyboard just because the software that goes with it, doesn't go with it for (from a user's perspective) no good reason whatsoever.

No one ever asked you, nor forced, to buy another keyboard. As outlined by Keychron and others the json method is still there for those that *do not comply or don't want to go through the due process for getting jsons merged*.

> software that goes with it

Given that the companies that pushed all these keyboard to the market did so by piggybacking the work of Open Source software, it is not for us, the Open Source community to support, fix or bend rules that have been followed and complied with by literally thousands of other creators.

No one is trying to change your mind, as rules are in place, we just explained the reasoning behind them.

**Comment by thany** [comment]
So is any collaboration with Keychron occurring?

I've notified them, but they might not take me seriously.

Things like should come with effort from both sides. If you really MUST have that sourcecode, and you are somehow convinced it is based on QMK (how could you know if the source allegedly is closed) then I would expect you to want to get this thing done. As it stands Keychron is fairly popular, so it is in more then only their interest to get this PR through, even if we conveniently forget about the end-user.

**Comment by Cipulot** [comment]
@thany 

> So is any collaboration with Keychron occurring?

It's up to the Keychron devs to comply with PR checks and requirements.

> you are somehow convinced it is based on QMK

We know for a fact, they have a fork of QMK with the code.

> how could you know if the source allegedly is closed
Above. Also, no one in the convo alleged that.

> their interest to get this PR through

Yes, it's in their interest and in the interest of the customers they sell the products to. Therefore their responsibility to follow the guidelines and PR checklists of the OS projects their product, that they sell, are based on.

As a note, refrain form making this PR as a chat log. The situation was laid out and explained extensively, it is up to the devs now to make the changes.

**Comment by yiancar** [comment]
I would like to add, for clarity's sake, the maintainers of any open source project dont bare the responsibility to chase product owners to make sure their project works with a released product. In contrast it is the other way round.
When a computing device claims to support the linux kernel, the people who support this product must make sure it does so. In a lot of cases they need to go contribute to it to make sure it does.

As @Cipulot has said this is not a pissing contest. If you disagree with our rules; that is your provocative. I hope we have explained clearly here for anyone who cares why this PR is not merged.

Cheers,
Yiangos

**Comment by thany** [comment]
> It's up to the Keychron devs to comply with PR checks and requirements.

That's not a very good way of cooperating. Either it comes from both sides, or you go full dictatorship.

> Above. Also, no one in the convo alleged that.

It was hinted: `As the keycron firmware cannot be opensourced`
But now you're finally pointing that there might be some form of proof.

Please collaborate with Keychron on this. Maybe they just need help. Don't act like you're the boss over everything VIA. It's a two-way road.

**Comment by thany** [comment]
Any progress? How is this two-way road going?

**Comment by thany** [comment]
Why close?

**Pull request closed without merging**
