### PR TITLE
Create timberwolf.json

### PR DESCRIPTION
**Pull request by Croktopus**
## Description

added Timber Wolf keyboard. contender for messiest .json maybe but it works surprisingly well

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/9876

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Croktopus** [comment]
qmk was merged btw

**Comment by Wilba6582** [comment]
Layout option #4 breaks the rule of exactly overlapping bounding boxes of keys. i.e. option 4,2 does not overlap exactly with 4,0 and 4,1.

The only way to fix this is to merge the split right shift (1.75U + 1U) into layout options 0,0 and 0,2 and the 1.75U shift into layout option 0,1 which means a full 2.75U shift won't be visible but the user can just assign right shift to both keys in this case.

**Comment by Croktopus** [comment]
Sorry, wasnt aware of that rule, thanks for the heads up and fixed

**Comment by Croktopus** [comment]
is this sufficient? should i add a bunch of blockers maybe?

**Comment by Croktopus** [comment]
so i went ahead and added more blocker labels and axed some stuff.

**Pull request merged**
