### PR TITLE
Create infinityce.json

### PR DESCRIPTION
**Pull request by mechlovin**
## Description

Add Infinity CE to VIA, PR  has been merged into master at: qmk/qmk_firmware/pull/8067
## Types of Changes

- [x] Adding a keyboard to VIA
- [ ] Changing a keyboard already in VIA
- [ ] Bug fix
- [ ] Documentation

## Checklist

- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] The QMK firmware can be built using QMK master repo.

### CODE REVIEW

**Comment by Wilba6582** [comment]
There are some legends on the keys that need to be removed.

Some keys in the Enter group have accent color which should be alpha or mod color (i.e. \ | should be alpha).

While this works as is, it would be better if the Enter layout options are off to the right side and grouped together, then the right shift layout options can also be grouped together. This is mainly so people looking at this as an example can follow it better.

**Comment by mechlovin** [comment]
Updated, thanks!

**Comment by Wilba6582** [comment]
Sorry to be pedantic ;-) but...

Still some puncuation on legends.

Homing keys have homing state checked.

The WKL blockers do not need switch matrix coordinates.

There should be "decal keys" for the 0.75U blockers in bottom row option 1.

(We are relying on some @olivia magic to make layout options work, which seems to be tolerating them being missing now)

Backspace, nav keys, system keys and some function keys can be made mod color.

(Even though VIA isn't showing mod color with the current Olivia++ Dark scheme, one day soon we will turn on a scheme with alphas, mods and accent colors).

**Comment by mechlovin** [comment]
I am graceful and really appreciate you for helping me correct this .json file.
Thank you and Olivia for developing the VIA for the community

**Comment by Wilba6582** [comment]
Almost there! 😂😂😂

Still some punctuation on legends. Comma, period.

F and J keys have homing state checked, shows as little bars.

Make the "blockers" keys with "Decal" checked, and the layout option `group,choice` in the bottom left legend like the others in that layout option choice.

**Comment by mechlovin** [comment]
Awsome! Thanks, you're a legend.
Good night!

**Comment by Wilba6582** [comment]
Thanks!

**Pull request merged**
