### PR TITLE
Update Apollo PCBs to use RGB matrix menu

### PR DESCRIPTION
**Pull request by Gondolindrim**
## Description

Updates Acheron Apollo PCBs to use the new RGB matrix menu.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/16817

Board is already present in the VIA repo, this is just an update.

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by wilba** [comment]
I recommend adding the `keycodes` to the V3 definitions as well: See here: https://www.caniusevia.com/docs/specification#keycodes

**Comment by wilba** [comment]
and fix up the indentation smh gondo do you even code?

**Comment by Gondolindrim** [comment]
Lighting keycodes enabled and identation fixed. Identation is a four character space. I just want to let this be noted and recorded:

`gOnDo Do yOU eVeN CoDe BRuH`

Thank you.

**Comment by Gondolindrim** [comment]
Lighting keycodes enabled and identation fixed. Identation is a four character space. I just want to let be noted and recorded that the phrase:

`gOnDo Do yOU eVeN CoDe BRuH sMh`

Is the nerdier version of

`gOnDo Do yOU eVeN liFT BRuH sMh`

Thank you.

**Pull request merged**
