### PR TITLE
Add Plaid 

### PR DESCRIPTION
**Pull request by yiancar**
## Types of Changes

- [x] Adding a keyboard to VIA
- [ ] Changing a keyboard already in VIA
- [ ] Bug fix
- [ ] Documentation

## Checklist

- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] The QMK firmware can be built using QMK master repo.

### CODE REVIEW

**Comment by yiancar** [comment]
QMK commit will be done by tomorrow

**Comment by Wilba6582** [comment]
@yiancar notify me when QMK master can build VIA-compatible firmware

**Comment by yiancar** [comment]
okidoki

**Comment by yiancar** [comment]
https://github.com/qmk/qmk_firmware/pull/8651

merged

**Pull request merged**
