### PR TITLE
feat: :sparkles: add config file for dactyl-manuform 4x6

### PR DESCRIPTION
**Pull request by AnotherStranger**
## Description

I added a config for the 4x6 dactyl manuform keyboard.

## QMK Pull Request 

The QMK PR is pending:
https://github.com/qmk/qmk_firmware/pull/19668

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by AnotherStranger** [comment]
@yiancar the pull request linked got merged!
Please re-open and re-review this PR. Thanks a lot!

**Comment by AnotherStranger** [comment]
@yiancar bump ;-)

**Comment by yiancar** [comment]
Cheers! sorry I didnt see it until the bump:)

**Comment by AnotherStranger** [comment]
> Cheers! sorry I didnt see it until the bump:)

Nothing to be sorry about!
Thank you for your help and awesome work! I really appreciate it!

**Pull request merged**
