### PR TITLE
add h87 g2 to via

### PR DESCRIPTION
**Pull request by hineybush**
## Description

Add V3-supported files for h87 gen 2 PCB

## QMK Pull Request 

](https://github.com/qmk/qmk_firmware/pull/20053)

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by wilba** [comment]
https://media.tenor.com/gaEpIfzxzPEAAAAC/pedro-monkey-puppet.gif

**Comment by hineybush** [comment]
am stupid

**Review by Xelus22 — APPROVED** [review]

**Review by Xelus22 — CHANGES_REQUESTED** [review]
Looks like you put in the wrong VID hiney.

**Comment by hineybush** [comment]
> Looks like you put in the wrong VID hiney. With your usual one being `0x04D8`

that's the Microchip VID for my 32u4 based boards, I'm using an arbitrary one for my STM32 boards. Turned out the first one I used was the same as another board.

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
