### PR TITLE
Knob Goblin VIA support

### PR DESCRIPTION
**Pull request by gknapp**
I've moved the configuration into a sub-directory and positioned the encoders in the VIA KLE data to match the physical board.

Notify @mrT1ddl3s

## Description

At present knobgoblin.json sits in the `src`, this PR moves it under the sub-directory `mrt1ddl3s`, the creator.

## QMK Pull Request 

Board already exists in [QMK with a via keymap](https://github.com/qmk/qmk_firmware/tree/master/keyboards/knobgoblin/keymaps/via).

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by mrT1ddl3s** [comment]
Looks good, no comments on my end.

**Comment by gknapp** [comment]
To the reviewer, how does VIA recognise the board prior to the definition being committed to this repo?

**Comment by wilba** [comment]
Enable the design tab in settings, then from the design tab, load the json

**Comment by gknapp** [comment]
Any ideas why VIA might not see the Knob Goblin? The vendor ID matches. VIA appears to parse / read the draft definition. TIA.
image

**Comment by wilba** [comment]
Yeah, that vendor/product ID matches, though it's different to the one in the repo already, which is 4b47:0000

I recall some weirdness with Linux and having to explicitly give permissions for software to access the raw HID interface of devices... maybe @olivia can answer this one.

**Comment by gknapp** [comment]
> Yeah, that vendor/product ID matches, though it's different to the one in the repo already, which is 4b47:0000
> 
> I recall some weirdness with Linux and having to explicitly give permissions for software to access the raw HID interface of devices... maybe @olivia can answer this one.

That's me testing, I changed the product ID to 1 (0x0031) in case having zero was an issue.

My Idobao 80 v2 is picked up immediately by VIA (under Linux), however the Knob Goblin is not. Presume the QMK configuration isn't quite right? Not sure what's been missed though, I worked through the docs and couldn't see anything wrong with what MrT1ddl3es has committed to the QMK repo.

**Comment by gknapp** [comment]
I notice that VIA takes circa 30-40 seconds to start on my system with my Knob Goblin plugged in and flashed with the VIA keymap. It does eventually load but the Knob Goblin isn't shown in the Configure Tab, even though the KLE draft is loaded successfully in the design tab.

It's like it's close but misconfigured somehow - is there a way to get a log / debug output out of VIA to help debug this?

**Comment by gknapp** [comment]
Original KLE left, revised right
knobgoblin-kle

**Comment by gknapp** [comment]
Can this change be merged?

**Pull request merged**
