### PR TITLE
Add LS_60.json

### PR DESCRIPTION
**Pull request by Weirdo-F**
## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/13851
## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by wilba** [comment]
There is no link to the merged PR which shows that VIA support for this keyboard is in QMK master already.

**Comment by Weirdo-F** [comment]
> There is no link to the merged PR which shows that VIA support for this keyboard is in QMK master already.

I have submitted qmk PR and filled in the link

**Comment by wilba** [comment]
It is not merged into QMK master

**Comment by Weirdo-F** [comment]
> It is not merged into QMK master

Do you want to wait until the merger is successful before submitting via PR?
I don't understand what you mean. Please check my link again.

**Comment by wilba** [comment]
> Do you want to wait until the merger is successful before submitting via PR?

yes, or comment here and I will reopen and merge

**Comment by Weirdo-F** [comment]
> yes, or comment here and I will reopen and merge

Oh, I see. thank you

**Comment by Weirdo-F** [comment]
@wilba This keyboard will be merged into QMK master. Can you open this PR?

**Comment by Weirdo-F** [comment]
@wilba This keyboard will be merged into QMK master. Can you open this PR?

**Pull request merged**
