### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by azhizhinov**
JSON for Reviung34 by gtips.

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/19694

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Xelus22** [comment]
Please fix PR comments and formatting. 
Please add QMK link

**Comment by azhizhinov** [comment]
Hello.
Sorry, I'm not experienced enough in this kind of things, so adding link here.
https://github.com/qmk/qmk_firmware/tree/master/keyboards/reviung/reviung34/keymaps/via
Where I should fix formatting?
Thanks for your time.

**Review by azhizhinov — COMMENTED** [review]
Thanks a lot.

**Comment by azhizhinov** [comment]
Hello.
Mostly done, I hope.
Thanks in advance.

**Comment by Xelus22** [comment]
Hi please move from `src/` folder to `v3/` folder

**Comment by azhizhinov** [comment]
> Hi please move from `src/` folder to `v3/` folder (seems the check is failing due to this)

So, I should move reviung34 folder from /src to /v3 and commit this change, right?

**Comment by Xelus22** [comment]
Yes

**Comment by azhizhinov** [comment]
Done.

**Pull request merged**
