### PR TITLE
Add support for LINE FRIENDS TKL

### PR DESCRIPTION
**Pull request by studiokestra**
## Description

Add VIA support for LINE FRIENDS TKL PCB.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/22172

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Review by Xelus22 — CHANGES_REQUESTED** [review]
`v3/studiokestra/line_friends_tkl/line_friends_tkl.json`

Please use the *same* tree structure as QMK without the word `friends`

**Comment by studiokestra** [comment]
@Xelus22 I should have mentioned that the vendor requested the PCB be renamed to LINE FRIENDS TKL to comply with their branding guideline. The QMK request for the rename was completed and merged here: https://github.com/qmk/qmk_firmware/pull/22310

Sorry for any confusion

**Comment by Xelus22** [comment]
@studiokestra thanks. Will have to wait for the develop->master merge.
https://docs.qmk.fm/#/breaking_changes?id=when-is-the-next-breaking-change

Next one is 26th November (in 6 days). Ping me if I forget to check this again. Thanks :)

**Review by Xelus22 — APPROVED** [review]
Waiting for develop->master merge... 26th nov

**Pull request merged**
