### PR TITLE
Add Sinc

### PR DESCRIPTION
**Pull request by nooges**
## Description

Add Sinc support

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/8986

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Wilba6582** [comment]
@Zambumon is triggered by the mod colored spacebars 😂

**Comment by Wilba6582** [comment]
The F row also needs some mod colors

**Comment by Wilba6582** [comment]
Split right shift 1.75U (9,4) is alpha colored, should be mod colored.

**Comment by nooges** [comment]
Fixed up the colors

**Comment by nooges** [comment]
QMK merge completed

**Pull request merged**
