### PR TITLE
[Keyboard] Add Quarkeys Z60 Solder Via file V3

### PR DESCRIPTION
**Pull request by tommyamoszhao**
## Checklist

- [ ] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by tommyamoszhao** [comment]
Just submitted firmware file to QMK master repository & verified, tested Z60-SD_VIA.json in online VIA already, works perfect. V2 json file seems to have conflict with latest qmk firmware, still trying to have it work. So upload the V3 json file for via first.

**Comment by yiancar** [comment]
Hello, Can you please provide the link to the QMK files or the PR request to QMK?

**Comment by tommyamoszhao** [comment]
Z67 has PRed, all checks passed, awaits to be merged. Here's the link: 
https://github.com/qmk/qmk_firmware/pull/19465
Thank you so much.

**Comment by yiancar** [comment]
Hello There usually we expect a PR to be opened after the QMK PR has been merged.
Typically we would close it and reopen it then but lets allow it this time round:)
Please ping me with a comment once the PR on QMK side has been merged.

**Comment by tommyamoszhao** [comment]
> Hello There usually we expect a PR to be opened after the QMK PR has been merged. Typically we would close it and reopen it then but lets allow it this time round:) Please ping me with a comment once the PR on QMK side has been merged.
Hi yiancar, thank you so much, I'll request a PR after relative firmware is merged next time. I'll keep an eye on the latest keyboard on qmk side, and comment here once it's merged. Cheers, TommyZ

**Comment by yiancar** [comment]
@tommyamoszhao looks like QMK requested some changes from you..

**Comment by yiancar** [comment]
Ok I will be closing this as its been almost a month and no update. Please feel free to ping me once qmk is checked in.

**Pull request closed without merging**
