### PR TITLE
Add KB30 keyboard

### PR DESCRIPTION
**Pull request by DOIO2022**
## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/19395

## Checklist

- [ ] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [ ] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [ ] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [ ] I have tested this keyboard definition using VIA's "Design" tab.
- [ ] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [ ] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by DOIO2022** [comment]
@Xelus22  HELLO, Could you tell me why this request was blocked,  this is the first time for my pulling request, could you tell me what need I do next step? Thank you !

**Comment by yiancar** [comment]
@DOIO2022 most likely at the time you didnt complete the checklist, can you please look over the checklist and make sure everything is correct and ticked off?

**Comment by DOIO2022** [comment]
@yiancar  I rebuild and the result is: "Error: Process completed with exit code 1" , Could you tell me  how can I resovle this problem? Thank you!

**Comment by yiancar** [comment]
The V2 definition (in src folder) must be changed:
Remove the menus and keycodes filed and replace it with:

```
  "lighting": {
    "extends": "qmk_rgblight",
    "underglowEffects": [
      ["All Off", 0],
      ["Solid Color", 1],
      ["Alphas Mods", 1],
      ["Gradient Up/Down", 1],
      ["Gradient Left/Right", 1],
      ["Breathing", 1],
      ["Band Saturation", 1],
      ["Band Value", 1],
      ["Pinwheel Saturation", 1],
      ["Pinwheel Value", 1],
      ["Spiral Saturation", 1],
      ["Spiral Value", 1],
      ["Cycle All", 1],
      ["Cycle Left/Right", 1],
      ["Cycle Up/Down", 1],
      ["Rainbow Moving Chevron", 1],
      ["Cycle Out/In", 1],
      ["Cycle Out/In Dual", 1],
      ["Cycle Pinwheel", 1],
      ["Cycle Spiral", 1],
      ["Dual Beacon", 1],
      ["Rainbow Beacon", 1],
      ["Rainbow Pinwheels", 1],
      ["Raindrops", 1],
      ["Jellybean Raindrops", 0],
      ["Hue Breathing", 1],
      ["Hue Pendulum", 1],
      ["Hue Wave", 1],
      ["Pixel Rain", 0],
      ["Pixel Flow", 0],
      ["Pixel Fractal", 1],
      ["Typing Heatmap", 1],
      ["Digital Rain", 0],
      ["Solid Reactive Simple", 1],
      ["Solid Reactive", 1],
      ["Solid Reactive Wide", 1],
      ["Solid Reactive Multi Wide", 1],
      ["Solid Reactive Cross", 1],
      ["Solid Reactive Multi Cross", 1],
      ["Solid Reactive Nexus", 1],
      ["Solid Reactive Multi Nexus", 1],
      ["Splash", 1],
      ["Multi Splash", 1],
      ["Solid Splash", 1],
      ["Solid Multi Splash", 1]
    ]
  },```

**Comment by DOIO2022** [comment]
@yiancar  I've deleted the KB30.JSON in  the V3 and need I close this request and pull another request? Thank you!

**Comment by yiancar** [comment]
No the v3 is mandatory and it was correct... the one under /src/ was the optional one...
please revert it back

**Comment by yiancar** [comment]
Hello its been over a month. I will close this PR please let me know when you fix it and I will open it again.

**Pull request closed without merging**
