### PR TITLE
Add support for the melody96

### PR DESCRIPTION
**Pull request by vlee489**
## Description

Adds support for the YMDK Melody 96 PCB

## QMK Pull Request 

[QMK Issues #9050](https://github.com/qmk/qmk_firmware/pull/9050)

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colours.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Wilba6582** [comment]
Some keys need to be changed to modifier or accent color:

image

**Comment by vlee489** [comment]
> Some keys need to be changed to modifier or accent color:
> 
> image

My bad just did a commit for correct it to this :
image

**Comment by vlee489** [comment]
The [QMK issue](https://github.com/qmk/qmk_firmware/pull/9050) tied to this is now merged.

**Comment by Shadowtrance** [comment]
Cols should be 9, not 10 btw. :)

**Comment by vlee489** [comment]
> Cols should be 9, not 10 btw. :)

What? I have tested this layout already and it works fine.

**Comment by vlee489** [comment]
> Cols should be 9, not 10 btw. :)

Nice Catch, looks like I can `Ctrl + C` properly 😓

**Pull request merged**
