### PR TITLE
Add XD60 keyboard PCB

### PR DESCRIPTION
**Pull request by se-bastiaan**
## Description

Add XD60 keyboard PCB support. It adds both the rev3 and v2 versions of the PCB, since the keymaps are the same.

Screenshot 2020-10-25 at 21 46 25
Screenshot 2020-10-25 at 21 46 50

## QMK Pull Request 

Already merged: https://github.com/qmk/qmk_firmware/pull/8829

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Raniita** [comment]
Hi! I already flashed my xd60 v2 to try the fw, but VIA program doesnt detect it (both linux and windows). The firmware flashed is the ones that appears on the via website (firmware downloads).

Any reasons? Something to debug? 

disclaimer: i dont know if it is the place to talk this... Sorry if doesnt :(

**Comment by se-bastiaan** [comment]
@Raniita no this is nice, let's figure it out together. I have a rev3 and only tested this by flashing the rev 2 firmware to my board. Did you use the design tab in Via to load the json?

**Comment by Raniita** [comment]
Wow... thats the piece that i forgot! Now loads fine...

I was follow VIA so long time but never give it a try hahaha.

One question. My layout its like 1u right shitf + arrow stack. On the layouts view, i dont see nothing that give me the result of that layout. Is this ok? It seems that we need one more slider to enable that

Thanks for answering too fast and for the work to port this PCB!

**Comment by se-bastiaan** [comment]
@Raniita 

Ah that makes sense.
I did not add a layout for arrows because I thought this would be enough for now. I have modified the layout a bit to support more.

**Comment by Raniita** [comment]
Tested the last commit. Already working fine with my layout!!!

Thank you!! You did it so well

**Pull request merged**
