### PR TITLE
Update t75.json

### PR DESCRIPTION
**Pull request by JackyJia73**
Change name to Part.1-75-HS

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/23344

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Cipulot** [comment]
@JackyJia73 if the board name changes, the folder structure names should too.

**Comment by JackyJia73** [comment]
Part.1-75-HS for folder and file name? @Cipulot  Thanks

**Comment by Cipulot** [comment]
@JackyJia73 If the board name changed, it only makes sense to change the folder names too accordingly to the new name. I see tho that the board is still called T75 in QMK so idk why the change is requested.
If you intend to go forward with the name change imo you should have consistency and have the name updated in QMK too. Apart from that, the folder structure should change from `v3/vertex/t75/t75.json` to `v3/vertex/part.1-75/part.1-75-HS.json`.

The board folder I assumed it to be `part.1-75` mainly bc I thought the HS was to signal Hotswap, so if a solder version will be made later the folder reflects that.
Ofc feel free to clarify if the assumptions above are wrong or something by suggesting or committing to your branch the appropriate naming. 

Thanks 😄

**Comment by JackyJia73** [comment]
@Cipulot Thank you so much. Your assumption is totally right. I already start a PR to change qmk name.
Thanks
😀

**Comment by JackyJia73** [comment]
change the directory and file name.

**Comment by JackyJia73** [comment]
https://github.com/qmk/qmk_firmware/pull/23403

**Comment by Cipulot** [comment]
https://github.com/the-via/keyboards/pull/2349 implements changes

**Pull request closed without merging**
