### PR TITLE
Add json for Work Louder Micro macropad

### PR DESCRIPTION
**Pull request by drashna**
## Description

Add VIA support for the Work Louder Micro board. 

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/17586

## Checklist

- [ ] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by yiancar** [comment]
Hello! Sadly the keyboard is not already merged into QMK main.
This is incorrectly checked in the checklist. Please reopen the PR once that is done as we are trying to clean the PR list a bit:)

Cheers!

**Comment by drashna** [comment]
Note: "via support for this keycode..." is not actually checked.  Intentionally. 

Also, no way for me to reopen this without opening a new PR. 

Also, why does #1303 get merged, when it's not been merged into QMK yet, and this gets closed?

**Comment by yiancar** [comment]
Yep a mistake happened there with 1303.
Let me know when your ready and I will reopen it for you!:)

**Comment by drashna** [comment]
> Let me know when your ready and I will reopen it for you!:)

QMK PR merged upstream :)

**Comment by yiancar** [comment]
Cheers thanks!

**Pull request merged**
