### PR TITLE
VIA Support for gBoards

### PR DESCRIPTION
**Pull request by germ**
Via support for g Heavy boards Gergo, GergoPlex and ButterStick. 

Waiting on https://github.com/qmk/qmk_firmware/pull/8262 to be merged currently.

- [x] Adding a keyboard to VIA
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.

### CODE REVIEW

**Comment by Wilba6582** [comment]
Nice...

The Gergoplex KLE has the thumb switches overlapping, could you move them apart so they don't?

I'd love to see the Faunchpad added as well 👍

**Comment by germ** [comment]
Done and done. 

Main issue with QMK for these kind of boards is they really only work because of [Combo/Chord](http://combos.gboards.ca/) shenanigans. Would love to move that to flash, but 1K is not nearly enough space for that lol.

(╯°□°）╯︵ ┻━┻

**Comment by Wilba6582** [comment]
Yeah, sorry, I thought Faunchpad was just a macropad and didn't have that stuff.

I'll merge after the QMK PR goes through as per usual process.

**Comment by unicorn855** [comment]
> Yeah, sorry, I thought Faunchpad was just a macropad and didn't have that stuff.
> 
> 
> 
> I'll merge after the QMK PR goes through as per usual process.

Why are some PRs for VIA sitting here for so long though? Can I help out somehow? @Wilba6582

**Comment by keyboard-magpie** [comment]
Can I just check what's holding this up at the mo?

**Comment by Wilba6582** [comment]
Waiting for the pull requests to QMK master to be merged.

**Comment by germ** [comment]
Yeah, they're sure taking their sweet fucking time :/

**Comment by unicorn855** [comment]
> Yeah, they're sure taking their sweet fucking time :/

I just checked the QMK PR#8262 you linked here, you apparently closed that and broke it up into PRs #8921-8929 (shouldn't those all be referenced here instead?), out of which eight are still open, so it might be reasonable to check all those and see how those can meet to requirements for merging before ranting on this PR here, since it is depending on the others to be merged first :)

**Comment by Wilba6582** [comment]
This PR is blocked and will not be looked at again until it is merged into QMK, the PRs for the merge are referenced here, and someone bumps this PR.

**Pull request closed without merging**
