### PR TITLE
Format Wasdat JSON to match Wasdat Code

### PR DESCRIPTION
**Pull request by fauxpark**
For OCD purposes. No functional changes, just converted to tabs, reduced the spacing between the F-row and number row and moved the `layouts` section to the bottom.

### CODE REVIEW

**Comment by Wilba6582** [comment]
We haven't set a style for the JSON definitions in the VIA repo, but up until now, all of them have used 2 space tabs (the default for Prettier Code Formatter extension for VS Code). Also, the convention has been to put the `labels` above the `keymap`

The WASD Code keyboard has a 0.5U spacing between the F-row and number row, so the original KLE matched the look of this keyboard. I'll let @maartenwut weigh in on this change.

**Comment by fauxpark** [comment]
The WASD Code is essentially just the WASD V2 with backlighting. I just figured they should be consistent, and used my Wasdat JSON as precedent.

**Comment by fauxpark** [comment]
Switched it around, now the Wasdat has been converted from tabs to spaces, and moved the `layouts` key to the top on both.

**Comment by Wilba6582** [comment]
Fair enough... I haven't been policing formatting here, just caring more about consistency of the KLE.

Thanks.

**Pull request merged**
