### PR TITLE
Add support for Hasu's Alps64

### PR DESCRIPTION
**Pull request by jja2000**
## Description

I've added support for VIA to the Alps64 by Hasu

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/9041

## Checklist

- [x] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [ ] I have tested this keyboard definition using VIA's "Design" tab.
I have tested it, but I've ran into a problem where the big ass enter is not properly slotted into the rest of the layout. Maybe you can help me with that:
image

- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by jja2000** [comment]
QMK PR is merged, just wondering what is needed to fix the Big Ass Enter thing. It looks like it's keeping whole keycap (including above the x-axis on the reversed L) in account when there's no physical keycap in place.

**Comment by ToniWonKanobi** [comment]
What's the status with this? I'd love to be able to use VIA for hasu's PCB 🙏

**Comment by trashcatt** [comment]
> 
> 
> What's the status with this? I'd love to be able to use VIA for hasu's PCB 🙏

It technically works. You'll just have to load the json file from https://github.com/the-via/keyboards/commit/89d99250820f59187df0c1bf4898f3c8a933681f into VIA

**Comment by wilba** [comment]
Thanks for the reminder, we need to fix the big ass enter bug.

**Comment by ToniWonKanobi** [comment]
So it's all good now, or ...? :D

**Comment by wilba** [comment]
We will fix the rendering bug first and then merge this.

**Comment by ToniWonKanobi** [comment]
> We will fix the rendering bug first and then merge this.

Has the rendering bug been fixed yet? :)

**Comment by ToniWonKanobi** [comment]
> > What's the status with this? I'd love to be able to use VIA for hasu's PCB 🙏
> 
> It technically works. You'll just have to load the json file from [89d9925](https://github.com/the-via/keyboards/commit/89d99250820f59187df0c1bf4898f3c8a933681f) into VIA.
> 
> At least that's what I had to do.

Also, where did you get the via-compatible `.hex` for the Alps64 PCB?

**Comment by yiancar** [comment]
Hello all! this has taken a while but... bug has been fixed.
Thank you for your patients:)

**Pull request merged**
