### PR TITLE
Ported ErgoDox EZ to Via

### PR DESCRIPTION
**Pull request by ifohancroft**
Ported ErgoDox EZ to Via

## Description

Ported ErgoDox EZ to Via. Tested on a Falba Tech ErgoDox. The lighting however, hasn't been ported as it uses RGB_MATRIX_ENABLE which Via doesn't support. There is a known workaround for getting the lighting to work (as done on the Moonlander) but I haven't implemented it as I can't test it on my ErgoDox.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/16804#event-6427791451

## Checklist

- [X] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [X] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [X] I have tested this keyboard definition using VIA's "Design" tab.
- [X] I have tested this keyboard definition with firmware on a device.
- [X] I have assigned alpha keys and modifier keys with the correct colors.
- [X] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by ifohancroft** [comment]
Ping

**Comment by ifohancroft** [comment]
Ping

**Comment by ifohancroft** [comment]
Ping

**Comment by yiancar** [comment]
Cheers thanks!
Keep an eye out for RGB_MATRIX_ENABLE, we will make it pretty easy to use soon:)

**Comment by ifohancroft** [comment]
That's great to hear! Thank you so much!

**Pull request merged**
