### PR TITLE
Add g1_65 keyboard

### PR DESCRIPTION
**Pull request by rojasa1990**
## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/12140

## Checklist

- [x] The VIA support for this keyboard is in QMK master already (MANDATORY)
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by wilba** [comment]
This requires a QMK PR link

**Comment by rojasa1990** [comment]
> This requires a QMK PR link

QMK PR link: https://github.com/qmk/qmk_firmware/pull/12140

**Comment by rojasa1990** [comment]
> ## Description
> ## QMK Pull Request
https://github.com/qmk/qmk_firmware/pull/12140
> ## Checklist
> * [x]  The VIA support for this keyboard is in QMK master already (MANDATORY)
> * [x]  The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
> * [x]  I have tested this keyboard definition using VIA's "Design" tab.
> * [x]  I have tested this keyboard definition with firmware on a device.
> * [x]  I have assigned alpha keys and modifier keys with the correct colors.
> * [x]  The Vendor ID is not `0xFEED`

**Comment by rojasa1990** [comment]
Added a QMK PR link.

________________________________

**Pull request merged**
