### PR TITLE
Add arc60h to VIA

### PR DESCRIPTION
**Pull request by Vertex-kb**
## Description
Add arc60h to VIA

## QMK Pull Request 
https://github.com/qmk/qmk_firmware/pull/18798

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Xelus22** [comment]
Hi, is there a need for the V2 (src folder) definition? Since thats only for backwards compatability but it seems your QMK PR is on latest master of VIA which uses V3

**Comment by Vertex-kb** [comment]
> Hi, is there a need for the V2 (src folder) definition? Since thats only for backwards compatability but it seems your QMK PR is on latest master of VIA which uses V3
I think it is necessary, thank you

**Comment by Xelus22** [comment]
Do you have any old firmwares produced on older QMK (before 0.19.x)? If not there is no reason to keep V2.

**Comment by Vertex-kb** [comment]
> Do you have any old firmwares produced on older QMK (before 0.19.x)? If not there is no reason to keep V2.

Because users already have a lot of PCBs in their hands, and their qmk version is lower than 19. So I think V2 is very necessary. Thanks！

**Review by Xelus22 — CHANGES_REQUESTED** [review]
Please move the files into `/vertex/arc60h` (should reflect QMK keyboard folder tree)

**Comment by Vertex-kb** [comment]
> Please move the files into `/vertex/arc60h` (should reflect QMK keyboard folder tree)

I have put in the correct folder.

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
