### PR TITLE
add kbd67rev2 via support

### PR DESCRIPTION
**Pull request by moyi4681**
add kbd67rev2 via support

## Checklist

- [ ] The QMK source code follows the guide here: https://caniusevia.com/docs/configuring_qmk
- [ ] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [ ] I have tested this keyboard definition using VIA's "Design" tab.
- [ ] I have tested this keyboard definition with firmware on a device.
- [ ] I have assigned alpha keys and modifier keys with the correct colors.
- [ ] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Wilba6582** [comment]
is this different to kbdfans/kbd67mkii/kbd67mkiisoldered.json ?

**Comment by moyi4681** [comment]
> is this different to kbdfans/kbd67mkii/kbd67mkiisoldered.json ?

it's different

**Comment by Wilba6582** [comment]
OK please move this to `src/kbdfans/kbd67rev2/kbd67rev2.json` for consistency with the other PCBs (even though this is a bit messy now and could do with some cleanup of names).

**Comment by Wilba6582** [comment]
Also, Esc key should be mod colored for consistency.

**Comment by moyi4681** [comment]
> Also, Esc key should be mod colored for consistency.
already changed, thanks!

**Comment by Wilba6582** [comment]
thanks

**Pull request merged**
