### PR TITLE
Add support for Saevus Cor65 PCB 

### PR DESCRIPTION
**Pull request by mechlovin**
## Description

Add VIA support for Cor65 PCB made by Mechlovin.
Thanks.

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/18872

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Xelus22** [comment]
Hey @mechlovin , this ones a bit confusing in terms of tree structure of this keyboard. Is this Zed65 or Cor65? 
Could you please clarify?

**Comment by mechlovin** [comment]
Hi @Xelus22, this is Cor65 PCB, base on Zed65 - our 65% platform PCB.

**Comment by mechlovin** [comment]
Should I change the name of PCB in info.json?

**Comment by Xelus22** [comment]
@mechlovin yeah it would be good if you could use the same tree structure as in QMK so its easier to differentiate between all the Zed65 variants?

like `v3/mechlovin/zed65/no_backlight/cor65/cor65.json`?

**Comment by mechlovin** [comment]
Sure, thank you.

**Comment by mechlovin** [comment]
Moved as your request.

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
