### PR TITLE
Add Rama Works M60-B

### PR DESCRIPTION
**Pull request by ToastyStoemp**
## Description

Add the via file for RamaWorks M60-B

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/19248

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by qnm** [comment]
Hi @Cipulot can you help me get this PR merged? I'm not sure what's blocking it. Works for me etc.

**Comment by qnm** [comment]
@wilba Will support for this board not be added to VIA?

**Comment by wilba** [comment]
No.

**Comment by qnm** [comment]
> No.

Noted, ty.

**Pull request closed without merging**
