### PR TITLE
Add Kibou/wendy file

### PR DESCRIPTION
**Pull request by biuboom-jun**
## QMK Pull Request 

[Add link to QMK Pull Request here.](https://github.com/qmk/qmk_firmware/pull/21150) 

## Checklist

- [x] The VIA support for this keyboard is **MERGED** in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have a V3 JSON version for this keyboard definition.**(MANDATORY)**
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by Xelus22** [comment]
Please paste in your QMK PR in the description.

**Comment by biuboom-jun** [comment]
> Please paste in your QMK PR in the description.

added

**Review by Xelus22 — CHANGES_REQUESTED** [review]
https://www.caniusevia.com/docs/layouts#kle-json-rules

please colour code your KLE

**Comment by biuboom-jun** [comment]
> https://www.caniusevia.com/docs/layouts#kle-json-rules
> 
> please colour code your KLE

Modified, please take a look

**Review by Xelus22 — CHANGES_REQUESTED** [review]
image

Please change this key to light grey. Everything else looks good :)

**Comment by biuboom-jun** [comment]
> image
> 
> Please change this key to light grey. Everything else looks good :)

Modified, please take a look

**Review by Xelus22 — APPROVED** [review]

**Pull request merged**
