### PR TITLE
Create vn.json

### PR DESCRIPTION
**Pull request by mfkiiyd**
add new keyboard ubest/vn

## Description

add new the keyboard ubest/vn  support in VIA

## QMK Pull Request 

https://github.com/qmk/qmk_firmware/pull/19263

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by yiancar** [comment]
Can you please provide a v3 JSON as well?

Cheers

**Comment by mfkiiyd** [comment]
> Can you please provide a v3 JSON as well?
> 
> Cheers

OK

**Comment by yiancar** [comment]
Cheers thanks!

**Comment by mfkiiyd** [comment]
> Cheers thanks!

Sorry, ubest/vn path was added incorrectly,  The correct path is ubest/vn

**Comment by mfkiiyd** [comment]
Please merge,  thanks!

**Comment by yiancar** [comment]
You need to create a new PR to fix it

**Pull request merged**
