### PR TITLE
Update Keychron q0, q1v1 and q2

### PR DESCRIPTION
**Pull request by lalalademaxiya1**
As the title, thank you.

## Description

- Renamed CYCKE in CYCKL_SPIRAL effect name with "CYCLE" for correct spelling.
- Renamed the keyboard name with "ansi, ansi_encoder, iso and iso_encoder" respectively for q1v1 and q2.
- Added encoder key to knob variants of q1v1 and q2 with e0 as the center label.
- Updated JSONs both in src and v3. 

## QMK Pull Request 

- https://github.com/qmk/qmk_firmware/pull/18598.
- https://github.com/qmk/qmk_firmware/pull/18713.

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by adophoxia** [comment]
Apart from the `CYCKL_SPIRAL` name correction, I do see changes for the Q0 for the 22 effects added compared to the 16 that is currently has right now in [`qmk:master`](https://github.com/qmk/qmk_firmware/blob/master/keyboards/keychron/q0/config.h#L53-L101). This may become a hinderance in getting this PR merged if the Q0 in QMK isn't updated to reflect those changes, which may result in issues like this.
* https://github.com/the-via/releases/issues/236

**Comment by yiancar** [comment]
@lalalademaxiya1 comments about the light? should I merge or not?

**Comment by lalalademaxiya1** [comment]
@yiancar Hi, I have updated the light effects and now the number of it for q0 has adapted to the current definition in qmk master,   
Please kindly assist me to merge the PR and as for adding new light effects for q0 we will pull new PR after updating in qmk master.

**Comment by adophoxia** [comment]
@lalalademaxiya1, seem like because of this PR you made earlier (see below), the JSONs for the regular Q0 (`rev_0130`) will need to be updated again to take account into the 21 effects it has now. 
* https://github.com/qmk/qmk_firmware/pull/19547

**Comment by yiancar** [comment]
@lalalademaxiya1 are you ok with mergin this now?

**Comment by lalalademaxiya1** [comment]
@yiancar Hi, I am sure this PR can be merge now, thanks~

**Pull request merged**
