### PR TITLE
add bella soldered keyboard

### PR DESCRIPTION
**Pull request by moyi4681**
QMK PR:https://github.com/qmk/qmk_firmware/pull/10381

### CODE REVIEW

**Comment by Wilba6582** [comment]
This needs a QMK PR

**Comment by moyi4681** [comment]
> This needs a QMK PR

https://github.com/qmk/qmk_firmware/pull/10381

**Comment by Kiileyy** [comment]
wonky

After manually adding in the JSON this is what the layout looks like, everything works and I can assign keys, just looks wonky.

**Comment by Wilba6582** [comment]
> wonky
> 
> After manually adding in the JSON this is what the layout looks like, everything works and I can assign keys, just looks wonky.

**Pull request closed without merging**
