### PR TITLE
Add dumbpad Macropad

### PR DESCRIPTION
**Pull request by medoix**
## Description

Add dumbpad

## QMK Pull Request 

https://github.com/keebd/qmk_firmware/tree/master/keyboards/dumbpad

## Checklist

- [x] The VIA support for this keyboard is in QMK master already **(MANDATORY)**
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by yiancar** [comment]
Hello @medoix we are not allowing a Vendor ID of `0xFEED`. Please change that from the QMK side:)
For a PR to be merged in VIA the full checklist must be ok.

Ill close the PR for now but please ping me once its ready and I will reopen it:)

**Comment by medoix** [comment]
@yiancar the PR has been merged in for QMK https://github.com/qmk/qmk_firmware/pull/17058

This PR altered the default vendorId and so i have now updated it for this PR

**Comment by yiancar** [comment]
Please Update it here as well

**Comment by medoix** [comment]
@yiancar the updates came through when you re-opened and the checks have all passed

**Comment by yiancar** [comment]
Cheers thanks!

**Pull request merged**
