### PR TITLE
Added GMMK Pro JSON for VIA support

### PR DESCRIPTION
**Pull request by WholesomeDucky**
Tested by WholesomeDucky

## Description
Added GMMK Pro .json for VIA support

## QMK Pull Request 
#12554

https://github.com/qmk/qmk_firmware/pull/12554

## Checklist

- [x] The VIA support for this keyboard is in QMK master already (MANDATORY)
- [x] The VIA definition follows the guide here: https://caniusevia.com/docs/layouts
- [x] I have tested this keyboard definition using VIA's "Design" tab.
- [x] I have tested this keyboard definition with firmware on a device.
- [x] I have assigned alpha keys and modifier keys with the correct colors.
- [x] The Vendor ID is not `0xFEED`

### CODE REVIEW

**Comment by armanatz** [comment]
@wilba FYI, QMK just merged @WholesomeDucky's changes. [Here is the commit](https://github.com/qmk/qmk_firmware/commit/7be4047df033cd1833ed3fa073d0c7954c063554) in master branch

**Comment by wilba** [comment]
@olivia did you get an apology from Glorious for promoting photos of fake GMK Olivia?

**Comment by WholesomeDucky** [comment]
@wilba I did not know about that. Did they do it intentionally or was it just a mediocre render or something?

**Comment by wilba** [comment]
image

**Comment by WholesomeDucky** [comment]
> image
> 
> 

Oh wow, not even a good clone....

I feel like they wanted to show people that render in live form and someone probably realized how hard it would be to get Olivia on such short notice and just said "screw it buy one on Ali"

**Comment by Gigahawk** [comment]
Man is this what Glorious meant by "issues out of our control"?
That's incredible.

For reference: https://www.reddit.com/r/glorious/comments/mzwhqm/an_official_glorious_dev_update_including/
image

**Comment by wilba** [comment]
> Man is this what Glorious meant by "issues out of our control"?

That post talks about delaying support until "post-launch", i.e. the cause is not because I didn't instantly merge this 3 days ago, thus they are referring to something else.

**Comment by GloriousBread** [comment]
> > image
> 
> Oh wow, not even a good clone....
> 
> I feel like they wanted to show people that render in live form and someone probably realized how hard it would be to get Olivia on such short notice and just said "screw it buy one on Ali"

@WholesomeDucky Actually some of us at Glorious have original Olivia sets. This post was not meant to promote any fake sets, but to promote the GMMK PRO. It's a photo one of our customers took and tagged us in. We have a policy of sharing their content (with written consent) if it meets certain visual standards.

Our employee on the social team is usually really good about finding content that meets said standards, but to be honest this is our first time in our company we're getting User Generated Content featuring clone sets. Since we released the PRO, we're being tagged in more and more content with these kinds of clone sets, vs what we were tagged in before which would be gaming keycaps, etc. We're a gaming brand first, so many on our team are not keyboard enthusiasts, therefore the person who sourced and posted this did not understand it would be offensive.

I took it down as soon as I saw it and gave a training session on what is and is not a real set. We're going to be much more careful now that we are not *just* a gaming brand. I'm sorry this happened, and as an enthusiast myself I was pretty mortified. I hope this explanation and apology helps.

**Comment by GloriousBread** [comment]
@olivia we are sorry this was posted, as we do not want to promote anything that would hurt members of the community. Especially not creators. I personally am a big fan of you and @wilba, and I wish I could buy an Olivia set to support you. I understand why people buy clones, but we do not support it. This was a mistake on our end, and we're sorry we did not catch it beforehand.

My inbox is always open for suggestions. Glorious does not want to butt heads with the enthusiast community. We want to learn from it and do right by it.

**Comment by WholesomeDucky** [comment]
@GloriousBread obviously I can't speak for others but at least in my eyes this seems reasonable. The product you've brought to market definitely sits in a unique "bridge" between typical gamer hardware and enthusiast hardware, and there are always going to be challenges associated with that.

As far as I'm concerned you're doing alright.

**Comment by GloriousBread** [comment]
Thank you, @WholesomeDucky. We hope so! We always want to be doing **_better_**, too. 

And I'm for real about the inbox thing. It's not some corporate BS speak. Email me anytime you want @olivia @wilba @WholesomeDucky, or hmu on Discord. I will make time for you to hear you out about anything. 

van(at)pcgamingrace(dot)com
or on Disc @ vnwld#1337

**Pull request merged**
